### ISSUE TITLE
UI/UX design for website

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#1]

**Comment by himanshu007-creator** [comment]
Have a look here first of all https://github.com/himanshu007-creator/SFC-foundations/issues/12

**Comment by vaibhav-305** [comment]
Hello, I would like to contribute. This is my first time contributing, will be a good exercise for me.
Can you please provide some more details for UI/UX like theme etc?
thank you

**Comment by vkassingh** [comment]
Do we have a discord/slack channel for communication?

**Comment by himanshu007-creator** [comment]
> Hello, I would like to contribute. This is my first time contributing, will be a good exercise for me.
> Can you please provide some more details for UI/UX like theme etc?
> thank you

Unfortunately, thats your job to come up with new ideas. I suggest to do some research and suggest something awesome. Rest welcome to the open-source culture!!

**Comment by himanshu007-creator** [comment]
> Do we have a discord/slack channel for communication?

HI , to promote open-ness and fair practices , we avoid to use any other platform for github. Whenever you feel to talk, use the particular isssue you wanna talk about and comment.

**Comment by srk224** [comment]
Hello, I would like to contribute.
I would start working on this as soon as possible and once I am done I will be sharing my mockups.

**Comment by sneha-nitdgp** [comment]
I'd like to contribute. Please assign this to me!

**Comment by himanshu007-creator** [comment]
@sneha-nitdgp   yes you can work on it. We just need an idea like how you will proceed. As we are redesigning everything so everything will be changes and so will the site structure. We just need to know how you are going to implement it. Prepare a prototype of code and send it within this week. Best of luck!

**Comment by abhish3k-11** [comment]
Hi @himanshu007-creator   I'm a UI/UX designer. I have worked on this type of projects before. I'd like to contribute to this issue.

**Comment by himanshu007-creator** [comment]
> Hi @himanshu007-creator I'm a UI/UX designer. I have worked on this type of projects before. I'd like to contribute to this issue.
hi @abhish3k-11 , glad you showed up! if @sneha-nitdgp is unable to do the task, you will be called. Till then wait🙂

**Comment by himanshu007-creator** [comment]
@abhish3k-11  go ahead!

**Comment by abhish3k-11** [comment]
@himanshu007-creator first of all thank you for assigning this to me. I read the guidelines and understood it. But can you please provide the info on what you want. I was thinking of first presenting my designs and then move forward. Please provide your views on this.

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator first of all thank you for assigning this to me. I read the guidelines and understood it. But can you please provide the info on what you want. I was thinking of first presenting my designs and then move forward. Please provide your views on this.

yes. You need to view the present website and suggest  color scheme, layout for new website that we are planning to make,

**Comment by abhish3k-11** [comment]
I'll 

> > @himanshu007-creator first of all thank you for assigning this to me. I read the guidelines and understood it. But can you please provide the info on what you want. I was thinking of first presenting my designs and then move forward. Please provide your views on this.
> 
> yes. You need to view the present website and suggest color scheme, layout for new website that we are planning to make,

Okayy I'll present to you a draft design with all those things that you mentioned in 3 days at most.

**Comment by himanshu007-creator** [comment]
@abhish3k-11  please send a draft by tomorrow, or this issue will be assigned to someone else.

**Comment by abhish3k-11** [comment]
This is wireframe (information layout). If you want to give advice on something, its most welcome. If you like it then please say so and after your comment I'll provide color scheme and fonts to be used (because first I wanna know your views on design) 

![Web 1920 – 2](https://user-images.githubusercontent.com/67673898/112939723-985ffe00-9149-11eb-8126-7ba509266e21.png)

**Comment by abhish3k-11** [comment]
It'll only take an hour or so to complete the small details so don't fret over that for now. If you like it, I'll do that in half a day.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by himanshu007-creator** [comment]
> Can I work on this issue?

its pretty much decided. so closing this issue, You can work on other issues. BEST OF LUCK!
