### ISSUE TITLE
Plan-chart of website

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#10]
Would love if someone could create similar site-plan for our website
![](https://landing.moqups.com/img/content/diagrams/site-maps/ecommerce-shop-sitemap-template.png)

**Comment by himanshu007-creator** [comment]
Have a look here first of all https://github.com/himanshu007-creator/SFC-foundations/issues/12

**Comment by SagarBapodara** [comment]
Hey @himanshu007-creator, I just came across your project from GSSoC'21. Looks like the website is pretty dynamic with payment gateways. I have worked & made many such websites using WordPress. Why don't you continue with WordPress, using Page Builders for the front end, & plugins for integrating various features you need. That will be much easy to maintain as well as an update in the future for those who will handle the website.

**Comment by himanshu007-creator** [comment]
> Hey @himanshu007-creator, I just came across your project from GSSoC'21. Looks like the website is pretty dynamic with payment gateways. I have worked & made many such websites using WordPress. Why don't you continue with WordPress, using Page Builders for the front end, & plugins for integrating various features you need. That will be much easy to maintain as well as an update in the future for those who will handle the website.

Hi @SagarBapodara , i welcome your suggestion, but the issue is , site will be used by a completely non-technical person, and i want to make it easiest-possible-thing. Therefore i am planning to say bye to wordpress. I wish to make it an awesome and simple website. That should have a feature that allows (ONLY ADMIN) to add articles/blogs along with associated images. I hope you would like to work on that , given your prior experience.  Raise an issue regarding the same, or just refer to issue #3 . Wishing to see you as a contributor😊.

**Comment by Subhangini** [comment]
Would like to work on this issue. Please assign it to me

**Comment by AnikaNarang9** [comment]
Hello, I started to build a basic layout of Home Page when I came across the plan-chart ,the plan chart is inclined towards the design of an e-commerce website it is very different from your original website .Could you please brief me about the sub-sections and what you expect them to be like .

**Comment by bug-debug-done** [comment]
Hello @himanshu007-creator can you please share exactly what you want for the website so that the end result will be accurate.

**Comment by mansijain980** [comment]
Hi @himanshu007-creator sir , i m a Gssoc participant . Please assign this to me.

**Comment by SAHU-01** [comment]
//cc @himanshu007-creator  we can make a plan chart as well as a git kanban board for the project so that even the participants lnow which tasks have been assigned and which issues they can work on,Let me know if you want a kanban board I can make that for the this project

**Comment by himanshu007-creator** [comment]
> //cc @himanshu007-creator we can make a plan chart as well as a git kanban board for the project so that even the participants know which tasks have been assigned and which issues they can work on,Let me know if you want a kanban board I can make that for the this project.

Sure! you can make the site map ( plan chart ) but the kanban board is not needed , done with majority of work

**Comment by rohank2502** [comment]
I think we will be having the same in read me we can also make this issue and issue #262  Common !
