### ISSUE TITLE
Modification and making more attractive contact page 

### ISSUE THREAD

**Issue by RoliGautam** [himanshu007-creator/SFC-foundations#101]
I want to modify the contact page by adding some font styles, background color , changes in submit button. 
Can you please assign me for this?

**Comment by Dhriti-Roy** [comment]
I'm a Participant in GSSOC'21. I am interested in contributing in the above issue. Kindly assign me this issue.

**Comment by subhasmitapradhan** [comment]
I would love to help @RoliGautam with this issue.

**Comment by Malvika18** [comment]
can i work on this.

**Comment by vatsalar** [comment]
I am interested in contributing to the above issue. Kindly assign me this issue.

**Comment by himanshu007-creator** [comment]
_sorted_
