### ISSUE TITLE
Adding arrow to the sliding images

### ISSUE THREAD

**Issue by RubenFalcao14** [himanshu007-creator/SFC-foundations#106]
![IMG_20210328_103653.jpg](https://user-images.githubusercontent.com/79042516/112743065-a5e28000-8fb1-11eb-8019-0fa0875104b0.jpg)
I would like to add arrows to the sliding section and remove the thing that is currently there if someone wants to manually go back and forth .

**Comment by RubenFalcao14** [comment]
I'm a GSSOC'21 participant and I would love to work on it .
Thank You

**Comment by himanshu007-creator** [comment]
Hi @RubenFalcao14 , i appreciate your advice, but we are NOT GOING TO MAKE any changes in old website, but going to create a new one!.
so try to solve issues with label gssoc🙂.
looking forward for your contributions.
you can try <a href="https://github.com/himanshu007-creator/SFC-foundations/issues/109">this</a> for now
