### ISSUE TITLE
link to CONTRIBUTING.md missing😐

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#109]
in <a href="">Readme.md</a> file, there is a problem. The href tag is there in line 34, but it points to <code>#</code>
it should point to <code>https://github.com/himanshu007-creator/SFC-foundations/blob/master/CONTRIBUTING.md</code>.
so fix this🙂

**Comment by RubenFalcao14** [comment]
Hii, I'm a GSSOC'21 participant and I would love to fix the issue.

**Comment by himanshu007-creator** [comment]
send a PR real soon😉

**Comment by Nishayadav-bit** [comment]
Hey @himanshu007-creator ,I would like to work on this issue . Please assign to me .
I'm a participant in GSSOC'21.

**Comment by RubenFalcao14** [comment]
I have made the pr , is it done or do I have to do anything more ?

**Comment by himanshu007-creator** [comment]
> I have made the pr , is it done or do I have to do anything more ?

have a look <a href="https://github.com/RubenFalcao14/SFC-foundations/pull/1">here</a> in the comment, i have told you what you need to do

**Comment by himanshu007-creator** [comment]
jobdone
