### ISSUE TITLE
Add Light Dark Mode

### ISSUE THREAD

**Issue by K-jais** [himanshu007-creator/SFC-foundations#113]
I can Add Light Dark Mode to all of the pages which adds another feature to this website and which just gives two choices to the user as whats its preferable UI is either light or dark.

**Comment by himanshu007-creator** [comment]
Thats a needed feature, bit first of all we need to make need to make new home page, and then all rest pages. After that , this will be considered

**Comment by K-jais** [comment]
> Thats a needed feature, bit first of all we need to make need to make new home page, and then all rest pages. After that , this will be considered

So sir, is the part that has already been made in the repository need to be changed completely?

**Comment by oneknucklehead** [comment]
@himanshu007-creator About the home page, do we have to make a Home page from scratch? and even if we did make the home page, what are the chances of it being selected, I mean there must be other people also who have made the homepage UI but what I wanted to ask is, is there a selection criterion or procedure? #help

**Comment by himanshu007-creator** [comment]
sorted
