### ISSUE TITLE
Revamp Events Page

### ISSUE THREAD

**Issue by RahulBansal0502** [himanshu007-creator/SFC-foundations#116]
The event page is so simple and static and also UI is also not so attractive. I want to revamp it. @himanshu007-creator @divyashukla23 Please assign this issue to me. I am a GSSOC 2021 participant.

**Comment by 1502shivam-singh** [comment]
Hey @RahulBansal0502, I would prefer that you first propose a wireframe or maybe a mockup for the events page. Do know that we are receiving multiple designs for the same page, so we have to compare your designs with the other one's before selecting it.

Make a PR with the event page mockup, and tag me or other mentors for review.

If you want to code the UI, then please wait a few days before we decide the design for this page.
All the best 👍

**Comment by RahulBansal0502** [comment]
ok

**Comment by himanshu007-creator** [comment]
sorted
