### ISSUE TITLE
In navbar  proper alignment is not there in the left side. It does not look good.

### ISSUE THREAD

**Issue by bug-debug-done** [himanshu007-creator/SFC-foundations#119]
![Screenshot from 2021-04-02 01-24-52](https://user-images.githubusercontent.com/75927761/113347171-6b326c00-9352-11eb-8eea-95dd5e6b6fd3.png)
the logo should be at the center of the "SFC FOUNDATIONS"

**Comment by himanshu007-creator** [comment]
old codebase issue
