### ISSUE TITLE
The button that navigate to the top of the page should have a arrow sign.

### ISSUE THREAD

**Issue by bug-debug-done** [himanshu007-creator/SFC-foundations#120]
![Screenshot from 2021-04-02 01-29-43](https://user-images.githubusercontent.com/75927761/113347747-412d7980-9353-11eb-8aa7-b5ee23b25edc.png)
the button on bottom of the page on right side.
please assign me this issue.

**Comment by bug-debug-done** [comment]
![Screenshot from 2021-04-02 01-29-43](https://user-images.githubusercontent.com/75927761/113347720-34a92100-9353-11eb-87dc-b2586305ab3a.png)

**Comment by pk-2345** [comment]
Hey ! @himanshu007-creator  can you please assign me this issue.

**Comment by himanshu007-creator** [comment]
Unfortunately, you are viewing old website. In new website, this feature is depricated.

**Comment by bug-debug-done** [comment]
@himanshu007-creator  I raised the issue on "2nd APRIL"

**Comment by himanshu007-creator** [comment]
@bug-debug-done , this is the new website ( under development )
