### ISSUE TITLE
Photos and text are not aligned properly

### ISSUE THREAD

**Issue by bug-debug-done** [himanshu007-creator/SFC-foundations#121]
![Screenshot from 2021-04-02 01-34-13](https://user-images.githubusercontent.com/75927761/113347960-95d0f480-9353-11eb-9bbf-bf207c35fbdf.png)
I will align the photo and text.

**Comment by Sejal260** [comment]
I can align the image and text properly.

**Comment by himanshu007-creator** [comment]
old codebase issue
