### ISSUE TITLE
Redesign  the Footer part

### ISSUE THREAD

**Issue by Mrinal81** [himanshu007-creator/SFC-foundations#123]
![Screenshot from 2021-04-02 01-39-02](https://user-images.githubusercontent.com/76482022/113348477-40491780-9354-11eb-8d37-999134ba9c08.png)

**Comment by Sejal260** [comment]
I will redesign the footer part

**Comment by himanshu007-creator** [comment]
the issue will be addressed soon as homepage template is about to be added.

**Comment by Sejal260** [comment]
Okay

**Comment by Sejal260** [comment]
@himanshu007-creator when will you provide me this issue?

**Comment by himanshu007-creator** [comment]
This issue is not needed as sent on old codebase
