### ISSUE TITLE
Photos are not Align in Events Page I will Align  the image in Events

### ISSUE THREAD

**Issue by Mrinal81** [himanshu007-creator/SFC-foundations#125]
![Screenshot from 2021-04-02 01-42-39](https://user-images.githubusercontent.com/76482022/113348894-d2512000-9354-11eb-9eb5-7a4fc400f506.png)

**Comment by divyashukla23** [comment]
Go ahead!

**Comment by Furquan712** [comment]
I would like to work on this , Will you assignee me

**Comment by Furquan712** [comment]
I would like to work on this, will you assign me?

**Comment by Sarthak-Agg** [comment]
can you assign me this, i can fix it

**Comment by ShrutiKhatri826** [comment]
I would like to contribute to this issue as a GSSOC'21 participant. Please assign it to me, hoping for a positive reply soon.

**Comment by himanshu007-creator** [comment]
Old website issue
