### ISSUE TITLE
Adding Place holder in contact form

### ISSUE THREAD

**Issue by n-coder2k** [himanshu007-creator/SFC-foundations#126]
I would like to add placeholder  in contact form.
I am gssoc participant please assign me this issue.

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by Rajashri14** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by himanshu007-creator** [comment]
Not needed issue. Thanks everyone for your interest. Please view other issues
