### ISSUE TITLE
ADD little Changes in Project section context.

### ISSUE THREAD

**Issue by starrohan999** [himanshu007-creator/SFC-foundations#127]
# Problem
I actually found a small thing while reading the project section that read more is not that bold. it should be bold visitors can easily check it out.

# Before image
![before](https://user-images.githubusercontent.com/71714344/113490153-f42ddc80-94e5-11eb-8eb3-32b6dbf88d2f.jpg)

# After Image
![after](https://user-images.githubusercontent.com/71714344/113490158-fee87180-94e5-11eb-8f35-4d08dc4f6a0a.jpg)

**Comment by starrohan999** [comment]
@himanshu007-creator sir, please assign to me this task.  i am gssoc'21 participant.

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by himanshu007-creator** [comment]
Old website issue
