### ISSUE TITLE
Links in the readme to open in a new tab

### ISSUE THREAD

**Issue by akshay1027** [himanshu007-creator/SFC-foundations#128]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
Links in the readme to open in a new tab so that it is easier for the user to navigate to GitHub codebase.

**Comment by rohank2502** [comment]
#143 Solved
