### ISSUE TITLE
Hover Selector Property 

### ISSUE THREAD

**Issue by AasthaCodex** [himanshu007-creator/SFC-foundations#129]
I would like to add hover selector property over 
who we are
our mission
our goal
Please assign it to me, It will look good. 
<img width="879" alt="website" src="https://user-images.githubusercontent.com/72413064/113511061-95b33d80-957b-11eb-8d82-e3e4d7cb52c6.PNG">

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by himanshu007-creator** [comment]
> I am a Gssoc participant , please assign me this issue.

hi @simranbhalla3 , new template for website is going to be uploaded soon, so be prepared to work on it. We wont be looking on issues with old website code. Have a look @ #12
