### ISSUE TITLE
Readme file enhancement

### ISSUE THREAD

**Issue by anirudhsai20** [himanshu007-creator/SFC-foundations#132]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

The Readme file can be enhanced by adding a list of all the Open Source programs in which this project was listed in. Also there are a few grammatical errors in the Readme file that needs correction.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by rohank2502** [comment]
@anirudhsai20  This issue is solved If you still like to do changes  in updated read me file please let us know here

**Comment by anirudhsai20** [comment]
Hi! I would still like to add a few changes that will enhance the Readme file.

**Comment by himanshu007-creator** [comment]
> Hi! I would still like to add a few changes that will enhance the Readme file.

details please?

**Comment by anirudhsai20** [comment]
I will add something like this:
![pda](https://user-images.githubusercontent.com/63279440/114862966-c8c3bf80-9e0c-11eb-9a9b-9bf96605d776.png)

**Comment by rohank2502** [comment]
I think idea is good but should not look Oversized you can add just logo or
something like that @himanshu007-creator/SFC-foundations
***@***.***>  will
tell you yes or no

**Comment by himanshu007-creator** [comment]
@anirudhsai20  cool, get started. Keep in mind the sizing thing, rest its awesome. Use GIF's, badeges (codecov specially).
Best of luck

**Comment by SugatoBagchi** [comment]
Hi,

I am a gssoc'21 participant and I would like to work on this issue.

It would be if you can assign me on this issue & elaborate a little more on it.

**Comment by himanshu007-creator** [comment]
@anirudh, you were inactive, so sorry, @sugatoBagchi, best of luck!

**Comment by rohank2502** [comment]
@himanshu007-creator  What changes are we looking for ?  I will like to suggest one of the deployment link can be shifted up below the title  or somewhere like that. This will help the new user to get to the link soon and also add the link in the description

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator What changes are we looking for ? I will like to suggest one of the deployment link can be shifted up below the title or somewhere like that. This will help the new user to get to the link soon and also add the link in the description

@SugatoBagchi , please note this , development link can be just after the badges. development link is GitHub pages link in present readme

**Comment by SugatoBagchi** [comment]
> > @himanshu007-creator What changes are we looking for ? I will like to suggest one of the deployment link can be shifted up below the title or somewhere like that. This will help the new user to get to the link soon and also add the link in the description
> 
> @SugatoBagchi , please note this , development link can be just after the badges. development link is GitHub pages link in present readme

Got it. Thanks. Will start working from today!👍

**Comment by rohank2502** [comment]
And Please let us know if any more changes you want to add @SugatoBagchi !! Great to have you in team ! Keep Working !
