### ISSUE TITLE
Fix the relevance attribute

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#137]
go to <code>index.html</code>
in line <a href="https://github.com/himanshu007-creator/SFC-foundations/blob/92855a6f43095ebbb28247d18f47ac2712d64368/index.html#L17">17</a>, change the following code.
<code>rel="text/css"</code>
 to 
<code>rel="stylesheet"</code>

**Comment by shairanshrawat** [comment]
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021
Thank you.

**Comment by himanshu007-creator** [comment]
go ahead!!
