### ISSUE TITLE
Enhance the footer section 

### ISSUE THREAD

**Issue by nidhivanjare** [himanshu007-creator/SFC-foundations#139]
I want to change the UI of the footer section. 
- Add iframe for map ---> address

I am a GSSOC'21 participant and would like to work on this issue.

**Comment by himanshu007-creator** [comment]
attach an SS

**Comment by nidhivanjare** [comment]
Something like this : 
<img width="676" alt="Screenshot 2021-04-09 at 12 45 44 PM" src="https://user-images.githubusercontent.com/55665104/114143232-82b0bc80-9931-11eb-8b57-b8df83c6d3d4.png">

**Comment by himanshu007-creator** [comment]
make these changes index.html

**Comment by nidhivanjare** [comment]
Sure , thanks

**Comment by himanshu007-creator** [comment]
ok

**Comment by nidhivanjare** [comment]
Hey, I received a mail from Rohan Kulkarni regarding the link broken issue. 
The link for the iframe is generated by
-> go to google maps 
-> type the address that you want to show on the website. 
-> click share and select "Embed a Map"
-> copy the HTML link and replace it with my code.
