### ISSUE TITLE
[BUG] [GSSOC' 21] Contact us link not working on navbar at index.html page of the website

### ISSUE THREAD

**Issue by Aditya201551** [himanshu007-creator/SFC-foundations#140]
On clicking the contact us button on the navbar the link does not take the user to the bottom of the page like other links, reference screenshot is added below:

![Screenshot 2021-04-10 103402](https://user-images.githubusercontent.com/32588231/114258987-4d1ada80-99e8-11eb-888e-c48b084e4a73.png)

@himanshu007-creator

**Comment by himanshu007-creator** [comment]
Yes , it's a feature,not a bug. Because contact form is under development right now.

**Comment by Aditya201551** [comment]
@himanshu007-creator okay, so should i close this issue then?

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator okay, so should i close this issue then?

Yes😅 but I am really looking for another PR from your side mate! Best of luck ⚡

**Comment by Aditya201551** [comment]
sure I will be creating a new issue now!
