### ISSUE TITLE
Deploy SFC website on Github pages 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#142]
If you want to know what exactly I am saying please visit this https://rohank2502.github.io/SFC-foundations/  I have deployed this website on GitHub pages of my version.

**Comment by rohank2502** [comment]
@himanshu007-creator  I will like if you take this issue on urgent basic this will help everyone of us

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator I will like if you take this issue on urgent basic this will help everyone of us

Yeah, will do that soon, but currently we are having some internal discussions about this , so its on  hold. But in till this month end, will surely do

**Comment by rohank2502** [comment]
> > @himanshu007-creator I will like if you take this issue on urgent basic this will help everyone of us
> 
> Yeah, will do that soon, but currently we are having some internal discussions about this , so its on hold. But in till this month end, will surely do

Ok !
