### ISSUE TITLE
Create Issue template 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#144]
I will like to make 2 issue templates 1. BUG 2. FEATURE REQUEST 3. DOCUMENTATION will start work as soon as I get assigned !

**Comment by himanshu007-creator** [comment]
just make a simple, all-in-one issue template, like include BUG/FEATURE?DOCUMENTATION check boxes in it

**Comment by rohank2502** [comment]
> 
> 
> just make a simple, all-in-one issue template, like include BUG/FEATURE?DOCUMENTATION check boxes in it

Ok will but I this we can make bug different so we can work on it more quick than a new feature

**Comment by rohank2502** [comment]
> > just make a simple, all-in-one issue template, like include BUG/FEATURE?DOCUMENTATION check boxes in it
> 
> Ok will but I this we can make bug different so we can work on it more quick than a new feature
@himanshu007-creator

**Comment by rohank2502** [comment]
Should I go up with single issue template or I think making 3 will be more convenient like bug feature and documentation as per my view lets get this final will work as you guide

**Comment by himanshu007-creator** [comment]
> Should I go up with single issue template or I think making 3 will be more convenient like bug feature and documentation as per my view lets get this final will work as you guide

single one  with category checkbox in starting that include 
- [x] BUG
- [x] FEATURE
- [x] DOCUMENTATION

**Comment by rohank2502** [comment]
> > Should I go up with single issue template or I think making 3 will be more convenient like bug feature and documentation as per my view lets get this final will work as you guide
> 
> single one with category checkbox in starting that include
> 
> * [x]  BUG
> * [x]  FEATURE
> * [x]  DOCUMENTATION

Okok got it
