### ISSUE TITLE
Social media icons with their respective colors on hover under social profiles

### ISSUE THREAD

**Issue by Harshit-Pathak** [himanshu007-creator/SFC-foundations#145]
<h3>Issue:</h3>
At present the color change on hovering over social media icons under Social Profiles is yellow for all

<h3>Enhancement:</h3>
Wanted to add respective colors to social media icons on hovering under Social Profiles<br>

Please assign me this issue as a gssoc'21 participant

**Comment by himanshu007-creator** [comment]
old website issue
