### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by avinashjha1320** [himanshu007-creator/SFC-foundations#146]
@himanshu007-creator @divyashukla23 I want to build contact us page where user can provide their detail. Can you please assign this task to me

**Comment by ineffable23** [comment]
This issue already exists.

**Comment by avinashjha1320** [comment]
@ineffable23 But nobody has made the page as I can't see any contact us page in the repository

**Comment by avinashjha1320** [comment]
Only the home page is there

**Comment by rohank2502** [comment]
If so please close the issue

**Comment by 1502shivam-singh** [comment]
@avinashjha1320 please refer to #115.
You can contribute your thoughts there, even though its already assigned.
Check #12 for some open issues.
