### ISSUE TITLE
Update Footer 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#148]
![Screenshot 2021-04-11 175335](https://user-images.githubusercontent.com/76584243/114304066-db798400-9aee-11eb-961b-e68e26033707.png)

Will like to add address and other things then will also like to include month and year of website creation this will remain as a memory to all  of us

**Comment by rohank2502** [comment]
@divyashukla23

**Comment by himanshu007-creator** [comment]
Will update you soon!

**Comment by rohank2502** [comment]
👍🏻

**Comment by himanshu007-creator** [comment]
@rohank2502 , this issue needs work, will do this comming week
