### ISSUE TITLE
change the logo of DARK mode toggle 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#149]
![Screenshot 2021-04-11 175838](https://user-images.githubusercontent.com/76584243/114304203-930e9600-9aef-11eb-9e50-aa87df737734.png)

Will like to change this toggle button to one which is standard I will like to add like DARK Mode and the button

**Comment by SAHU-01** [comment]
//cc @rohank2502  would you like to have a new Dark button design or like you want an entire dark mode featture for the webpage andd that we have to design that page.
I'd like to take up this issue I'll add a demo design below let me know if it's to your liking.

**Comment by rohank2502** [comment]
> //cc @rohank2502 would you like to have a new Dark button design or like you want an entire dark mode featture for the webpage andd that we have to design that page.
> I'd like to take up this issue I'll add a demo design below let me know if it's to your liking.

Sorry but I created this issue to work on this !

**Comment by SAHU-01** [comment]
OO I'm so sorry!

**Comment by rohank2502** [comment]
> OO I'm so sorry!

Its fine no issues :)

**Comment by rohank2502** [comment]
Please assign the issue
