### ISSUE TITLE
[ENHANCEMENT] [GSSOC' 21]  Making new good looking button for dark mode

### ISSUE THREAD

**Issue by Aditya201551** [himanshu007-creator/SFC-foundations#150]
![Screenshot 2021-04-11 235628](https://user-images.githubusercontent.com/32588231/114316613-ebf72200-9b21-11eb-8796-fd043c6de46d.png)

![Screenshot 2021-04-11 235718](https://user-images.githubusercontent.com/32588231/114316625-f1546c80-9b21-11eb-9e13-254dc7b8ff0d.png)

@himanshu007-creator

**Comment by Aditya201551** [comment]
@himanshu007-creator I have added the feature, it can be deployed as soon I am assigned


https://user-images.githubusercontent.com/32588231/114318574-37fa9480-9b2b-11eb-82f6-75d3cd5ee335.mp4

**Comment by rohank2502** [comment]
> @himanshu007-creator I have added the feature, it can be deployed as soon I am assigned
> 
>  comp.mp4

I have already created issue

**Comment by Aditya201551** [comment]
> I have already created issue

But I have already created the feature, well it's up to @himanshu007-creator now

**Comment by rohank2502** [comment]
> > I have already created issue
> 
> But I have already created the feature, well it's up to @himanshu007-creator now

Was you assigned or told by him to do that task ?

**Comment by Aditya201551** [comment]
> > > I have already created issue
> > 
> > 
> > But I have already created the feature, well it's up to @himanshu007-creator now
> 
> Was you assigned or told by him to do that task ?

nope but I just made a new issue

**Comment by rohank2502** [comment]
Please keep in mind don't work on issue until u are assigned this is not
way to work 👍🏻

**Comment by Aditya201551** [comment]
@rohank2502 thank you for teaching me what to do and what not to, I just added this feature in my local system and its so simple feature that it took just few lines of code to add so I added this to my local code(its not even pushed to origin) as I wanted to see how it would look so you can work according to your ethics and let me do whatever I want 💀

**Comment by himanshu007-creator** [comment]
@Aditya201551 and @rohank2502  chillax guys, you both are correct in your own explanations.  Rohan had created the issue earlier . Going by the good opensource practice, it is advised to follow a sequence of steps to cater to everyone's needs. We need to be inclusive
1) before opening an issue , try to see if its already there or not
2) after creating an issue, wait for admin to assign it to you ( in case you wanna work)
3) if you are commenting on other issues, see the whole convo. as issues are assigned on first-come-first-serve basis.
 SO i hope it is clear now what needs to be done. #149 will remain the valid issue. @aditi1403 you can colab with rohan there for the designing and you both can implement it together as well.
 And don't mind if I sound rude or authoritative, I want you both to have a good time here✨

**Comment by rohank2502** [comment]
> 3\. nd you both can implement it together as well.
>     And don't mind if I sound rude or authoritative, I want you both to have a good time here✨

Thanks !! 
and sorry @Aditya201551

**Comment by Aditya201551** [comment]
@himanshu007-creator sure, I understood
