### ISSUE TITLE
Dark/Light Mode Image Loading Error

### ISSUE THREAD

**Issue by Rohan27s** [himanshu007-creator/SFC-foundations#155]
## Issue Type:
[ ! ] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

- There is bug in loading Dark/Light mode changing image 

## **Possible solution**

- I have knowledge of this issue and can solve it. So I would like to work
on this issue under GSSOC21

## **Screenshots**
![image](https://user-images.githubusercontent.com/74227860/114663217-95533900-9d17-11eb-811b-92ba30cc070a.png)

- If applicable, add screenshots to help explain your problem.

**Comment by rohank2502** [comment]
Solved this issue please check  !! @Rohan27s
