### ISSUE TITLE
Smooth Scrolling in website

### ISSUE THREAD

**Issue by arpit456jain** [himanshu007-creator/SFC-foundations#157]
## Issue Type:
[x] Bug Report 
[x]  Feature Request 
[  ] Documentaion

## **Describe the bug**
As of now scrolling is very fast which is not looking good

## **Possible solution**

It should be little bit slow , it will look pretty nice

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by himanshu007-creator** [comment]
<code>
html{
  scroll-behavior: smooth;
}
</code>
You mean this right?

**Comment by arpit456jain** [comment]
> ` html{ scroll-behavior: smooth; } ` You mean this right?
> put it in css>style.css

Yes

**Comment by arpit456jain** [comment]
@himanshu007-creator kindly review my PR and add these same labels to it before merging

**Comment by arpit456jain** [comment]
thanks @himanshu007-creator .
I will make a Pr for preloader in sometime
