### ISSUE TITLE
[Gssoc21] Back to top button

### ISSUE THREAD

**Issue by arpit456jain** [himanshu007-creator/SFC-foundations#158]
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

## **Describe the bug**

There is no back to top button

## **Possible solution**

I would like to add a back to top button which will scroll to top automatically

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by himanshu007-creator** [comment]
not needed rn, but will consider for future
