### ISSUE TITLE
[Gssoc21] News section is not responsive

### ISSUE THREAD

**Issue by arpit456jain** [himanshu007-creator/SFC-foundations#159]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

<img width="960" alt="sfc" src="https://user-images.githubusercontent.com/55352601/114674543-f6353e00-9d24-11eb-9b34-7b914a94c49b.png">

**Comment by himanshu007-creator** [comment]
@arpit456jain  nice, you can work on this, send a PR . Discuss this here with @SnehaVeerakumar

**Comment by SnehaVeerakumar** [comment]
@arpit456jain I can fix it, thank you for spotting it out. Can you raise an issue regarding a separate page for any of the section in navigation bar !!
That would be really helpful.

**Comment by arpit456jain** [comment]
> @arpit456jain I can fix it, thank you for spotting it out. Can you raise an issue regarding a separate page for any of the section in navigation bar !!
> That would be really helpful.

I can make a separate page for contact section

**Comment by SnehaVeerakumar** [comment]
> > @arpit456jain I can fix it, thank you for spotting it out. Can you raise an issue regarding a separate page for any of the section in navigation bar !!
> > That would be really helpful.
> 
> I can make a separate page for contact section

"About us" page please. Level-3 can be given for that.
Contact us is already in progress

**Comment by arpit456jain** [comment]
> > > @arpit456jain I can fix it, thank you for spotting it out. Can you raise an issue regarding a separate page for any of the section in navigation bar !!
> > > That would be really helpful.
> > 
> > 
> > I can make a separate page for contact section
> 
> "About us" page please. Level-3 can be given for that.
> Contact us is already in progress

ok

**Comment by arpit456jain** [comment]
I 

> > > @arpit456jain I can fix it, thank you for spotting it out. Can you raise an issue regarding a separate page for any of the section in navigation bar !!
> > > That would be really helpful.
> > 
> > 
> > I can make a separate page for contact section
> 
> "About us" page please. Level-3 can be given for that.
> Contact us is already in progress

@himanshu007-creator  I had raised a issue for this. Can i close this issue now?

**Comment by SnehaVeerakumar** [comment]
@arpit456jain Yes, go ahead.
