### ISSUE TITLE
ISSUE TEMPLATE

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#16]

**Comment by himanshu007-creator** [comment]
Have a look here first of all https://github.com/himanshu007-creator/SFC-foundations/issues/12

**Comment by Subhangini** [comment]
I would like to work on this .
Please assign it to me

**Comment by himanshu007-creator** [comment]
> I would like to work on this .
> Please assign it to me

 HI @Subhangini GSSOC will begin on 1st march, then only issues will be alotted . Please have a look here https://github.com/himanshu007-creator/SFC-foundations/issues/12

**Comment by Subhangini** [comment]
>HI @Subhangini GSSOC will begin on 1st march, then only issues will be alotted . Please have a look here #12

Ok @himanshu007-creator .Will wait till then.

**Comment by Ankita297** [comment]
I would like to work on this issue under GSSOC ?
Please assign me

**Comment by vismitap** [comment]
I would like to work on this as a part of GSSOC! Please assign me this!

**Comment by himanshu007-creator** [comment]
@Subhangini   yes you can work on it. We just need an idea like how you will proceed. As we are redesigning everything so everything will be changes and so will the site structure. We just need to know how you are going to implement it. Prepare a prototype of code and send it within this week. Best of luck!

**Comment by Subhangini** [comment]
![s1](https://user-images.githubusercontent.com/68437435/110454954-e1460900-80ed-11eb-9df2-1a8502101905.jpg)
![s2](https://user-images.githubusercontent.com/68437435/110455174-1c483c80-80ee-11eb-8b7e-79de595a2c2d.jpg)

This is my code snippet .

**Comment by Subhangini** [comment]
@himanshu007-creator is it sufficient  for issue template or i should change something please review it.
