### ISSUE TITLE
[Gssoc'21] Preloader is not responsive in mobile view

### ISSUE THREAD

**Issue by arpit456jain** [himanshu007-creator/SFC-foundations#160]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

https://user-images.githubusercontent.com/55352601/114675100-83789280-9d25-11eb-80bd-858d8aca93a2.mp4

**Comment by rohank2502** [comment]
Cool, I think changing size units will work! @himanshu007-creator assigns him the issue if he completes it's great else I will take this!

**Comment by himanshu007-creator** [comment]
cool, send a PR for this one

**Comment by arpit456jain** [comment]
> cool, send a PR for this one

@himanshu007-creator kindly assign me this issue under GSSoC'21 .
I will make a pr in an hour

**Comment by arpit456jain** [comment]
@himanshu007-creator kindly review my PR
