### ISSUE TITLE
Adding google map feature on foundation's website

### ISSUE THREAD

**Issue by shrishti-c** [himanshu007-creator/SFC-foundations#163]
## Issue Type:
Feature Request

## **Describe the bug**

It is really important to have the Google Maps Platform set up for websites to ensure your website is being seen on the web through Google's search engine.

## **Possible solution**

Adding a Google Map with a Marker to Your Website bookmark.

**Comment by shrishti-c** [comment]
@himanshu007-creator  This would be great for SEO of website

**Comment by himanshu007-creator** [comment]
sure, ! i have a person, you both can collaborate! but for now, gove me some details of your solution, at at the end what will be the delievrables

**Comment by shrishti-c** [comment]
Sir here we will be using google map API to integrate our website . Then we can show the location of NGO office on the website through google maps.

**Comment by himanshu007-creator** [comment]
ok you cab send a PR

**Comment by Furquan712** [comment]
I would like to work on this, will you assign me?
