### ISSUE TITLE
Make toggle button action smooth

### ISSUE THREAD

**Issue by arpit456jain** [himanshu007-creator/SFC-foundations#168]
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

## **Describe the bug**
As you can see in picture the toggle button is not looking good in dark mode because of its white background
<img width="960" alt="sfc tg" src="https://user-images.githubusercontent.com/55352601/114815937-d78e8000-9dd4-11eb-8ffa-dbb0f21cb947.png">

## **Possible solution**

I can replace it with this
<img width="960" alt="toggle" src="https://user-images.githubusercontent.com/55352601/114816049-073d8800-9dd5-11eb-96f6-e6acceace6cc.png">

**Comment by himanshu007-creator** [comment]
Button is fine, you can work on the animation part, make it smooth , rather than abrupt. theme transition should also be smooth

**Comment by arpit456jain** [comment]
> Button is fine, you can work on the animation part, make it smooth , rather than abrupt. theme transition should also be smooth

@himanshu007-creator I don't think we can make its animations smooth because all it have is 2 images that's it how can i add animations to it
I had made this toggle button with out any image with animations .

https://user-images.githubusercontent.com/55352601/114817950-897b7b80-9dd8-11eb-9d70-81e22151de81.mp4

**Comment by arpit456jain** [comment]
> Button is fine, you can work on the animation part, make it smooth , rather than abrupt. theme transition should also be smooth

@himanshu007-creator i just notice there is also a but in that button .
If you activate dark mode and refreesh the page it will go back in light mode it is of no use

**Comment by arpit456jain** [comment]
@himanshu007-creator

**Comment by rohank2502** [comment]
@arpit456jain  Hey , Nice Work will look your code and will let you know tomorrow! Sorry for  a bit delay hope you don't mind !

**Comment by arpit456jain** [comment]
> @arpit456jain Hey , Nice Work will look your code and will let you know tomorrow! Sorry for a bit delay hope you don't mind !

Yeah it's fine

**Comment by rohank2502** [comment]
Hey, @arpit456jain Work is nice but have to look code once Please give a Pull request add me as a reviewer. Your code will be reviewed so it doesn't disturb the current project. And If it works fine then we will get this merged

**Comment by arpit456jain** [comment]
Ok making a PR

**Comment by arpit456jain** [comment]
@rohank2502 i dont't know you noticed or not but there is bug in current dark mode 

as you can see in this video when  I activated dark mode and refresh the page it should be dark mode .
It is not working properly

**Comment by arpit456jain** [comment]
> Hey, @arpit456jain Work is nice but have to look code once Please give a Pull request add me as a reviewer. Your code will be reviewed so it doesn't disturb the current project. And If it works fine then we will get this merged

@himanshu007-creator @rohank2502 kindly review my PR
