### ISSUE TITLE
Feed.png is unresponsive at mob version 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#169]
## Issue Type:
[ x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

The size of feed .png is large than required 

## **Possible solution**

We can use responsive units 

## **Screenshots**

![Screenshot 2021-04-15 102908](https://user-images.githubusercontent.com/76584243/114816254-66030180-9dd5-11eb-87bf-536bc4882d6f.png)

**Comment by rohank2502** [comment]
@himanshu007-creator  Will like to fix this!

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Will like to fix this!

@SnehaVeerakumar  she will work it, its her call

**Comment by rohank2502** [comment]
> > @himanshu007-creator Will like to fix this!
> 
> @SnehaVeerakumar she will work it, its her call

OK no Issues was there any issue for this ?

**Comment by SnehaVeerakumar** [comment]
@rohank2502 can work on this issue.

@himanshu007-creator please assign him.

**Comment by rohank2502** [comment]
> @rohank2502 can work on this issue.
> 
> @himanshu007-creator please assign him.

Ok, Thanks!

**Comment by himanshu007-creator** [comment]
#273
