### ISSUE TITLE
PULL REQUEST TEMPLATE

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#17]

**Comment by himanshu007-creator** [comment]
Have a look here first of all https://github.com/himanshu007-creator/SFC-foundations/issues/12

**Comment by Subhangini** [comment]
I would like to work on this.
Please assign it to me

**Comment by himanshu007-creator** [comment]
> I would like to work on this.
> Please assign it to me

 HI @Subhangini GSSOC will begin on 1st march, then only issues will be alotted . Please have a look here https://github.com/himanshu007-creator/SFC-foundations/issues/12

**Comment by Subhangini** [comment]
Ok @himanshu007-creator .Will wait till then.

**Comment by chehak123** [comment]
https://github.com/syedibrahim/Pharmacy-Management-System

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by himanshu007-creator** [comment]
@Subhangini   yes you can work on it. We just need an idea like how you will proceed. As we are redesigning everything so everything will be changes and so will the site structure. We just need to know how you are going to implement it. Prepare a prototype of code and send it within this week. Best of luck!

**Comment by mansijain980** [comment]
@himanshu007-creator I would like to work on it . 
Please assign it to me.
Thanks.
