### ISSUE TITLE
Add pages for 3 Project 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#170]
## Issue Type:
[  ] Bug Report 
[ x]  Feature Request 
[  ] Documentaion

## **Describe the bug**

Add Pages for Our 3 Projects 

## **Possible solution**

For now we can add the same data on Wordpress website so we can get an idea for improvement !

**Comment by rohank2502** [comment]
@himanshu007-creator  Can we start for this ?

**Comment by SnehaVeerakumar** [comment]
@rohank2502 Go ahead and work on this.

@himanshu007-creator kindly assign him.

**Comment by rohank2502** [comment]
> ead and work on this.

Cool ! I will start work on this tomorrow and update you with all three pages within 3 days will it be ok !

**Comment by SnehaVeerakumar** [comment]
Yeah, 1st update by Sunday would be fine.

**Comment by rohank2502** [comment]
> Yeah, 1st update by Sunday would be fine.

Cool @himanshu007-creator  Please assign

**Comment by rohank2502** [comment]
@himanshu007-creator  We have created all three pages for projects !!

**Comment by himanshu007-creator** [comment]
done
