### ISSUE TITLE
[Gssoc'21] Make a separate page of about us

### ISSUE THREAD

**Issue by arpit456jain** [himanshu007-creator/SFC-foundations#171]
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

## **Describe the bug**

I would like to give it a try to make a separate page for about section as suggested in issue  #159 
## **Possible solution** 

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by SnehaVeerakumar** [comment]
Start working on rhis issue. Don't alter nav bar and footer.
Get the necessary inputs from @himanshu007-creator. You can send a personal text to him in discord.

You will soon be assigned in this issue by @himanshu007-creator

**Comment by arpit456jain** [comment]
@himanshu007-creator I had a about us page kindly review it and assign this issue to me

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/114912818-1573be80-9e3e-11eb-8d29-a1e066fc2f99.mp4

**Comment by SnehaVeerakumar** [comment]
@arpit456jain color :pink/red is not so good. Space between "about us" and the info can be reduced.

Don't worry about assigning. You will be assigned this issue with level-3 tag. Work on this issue.

**Comment by arpit456jain** [comment]
> @arpit456jain color :pink/red is not so good. Space between "about us" and the info can be reduced.
> 
> Don't worry about assigning. You will be assigned this issue with level-3 tag. Work on this issue.

Yeah colours can be changed anytime I just wanted to show the functionality.
And i will reduce the space don't worry

**Comment by SnehaVeerakumar** [comment]
@arpit456jain cool !

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115044513-34805800-9ef3-11eb-8cbe-0205f32332fa.mp4

**Comment by arpit456jain** [comment]
@himanshu007-creator
