### ISSUE TITLE
[ENHANCEMENT] [GSSOC' 21] Enhancing night mode feature

### ISSUE THREAD

**Issue by Aditya201551** [himanshu007-creator/SFC-foundations#172]
## Issue Type:
- [ ] Bug Report 
- [ ]  Feature Request 
- [ ] Documentaion
- [x] Enhancement

## **Describe the feature**

- Adding transition to the night mode button and the whole page

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/32588231/114847230-1cc5a880-9dfb-11eb-98dd-de4ab226ea23.mp4

its just an enhancement for dark mode

@himanshu007-creator

**Comment by himanshu007-creator** [comment]
go ahead!! awesome!
