### ISSUE TITLE
[GSSOC' 21] [FAVICON] Adding foundation logo to the title tab

### ISSUE THREAD

**Issue by Aditya201551** [himanshu007-creator/SFC-foundations#173]
## Issue Type:
- [ ] Bug Report 
- [ ] Documentaion
- [x]  Feature Request 

## **Describe the feature**

- Adding foundation logo on the title tab of the web browser as page loads(favicon)

## **Possible solution**

- using favicon

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

screenshot not applicable

@himanshu007-creator

**Comment by himanshu007-creator** [comment]
please attach a ss ,

**Comment by himanshu007-creator** [comment]
review after a screenshot @SnehaVeerakumar

**Comment by SnehaVeerakumar** [comment]
Sure @himanshu007-creator

**Comment by Aditya201551** [comment]
okay then I am start working then I will attach the ss

**Comment by Aditya201551** [comment]
@SnehaVeerakumar here is the screenshot of the added favicon:

![Screenshot (80)](https://user-images.githubusercontent.com/32588231/114925199-6db1bd00-9e4c-11eb-9d11-863614308670.png)

![Screenshot 2021-04-16 004138](https://user-images.githubusercontent.com/32588231/114925281-891cc800-9e4c-11eb-8c4c-41f19d333e49.png)

Please tell me if any change needed

**Comment by SnehaVeerakumar** [comment]
Yeah it's good @Aditya201551

**Comment by Aditya201551** [comment]
so should i add the pr?

**Comment by SnehaVeerakumar** [comment]
Yes, do it

**Comment by Aditya201551** [comment]
@SnehaVeerakumar added please review it
