### ISSUE TITLE
I can create a separate page for 'project' section

### ISSUE THREAD

**Issue by CMELAKKIA** [himanshu007-creator/SFC-foundations#174]

**Comment by SnehaVeerakumar** [comment]
Go ahead. You will soon be assigned by @himanshu007-creator 

Get the necessary inputs from discord personal chat of @himanshu007-creator

**Comment by rohank2502** [comment]
@SnehaVeerakumar  Copy of #170

**Comment by SnehaVeerakumar** [comment]
@CMELAKKIA create an issue about events page and close this please.
