### ISSUE TITLE
News Section

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#179]
## Issue Type:
[ x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

When we click the new section Readmore we get directed to starting of the page 

## **Possible solution**

We can add a link to readme of a direct news source or we can make a separate page and add the whole news there

**Comment by rohank2502** [comment]
@SnehaVeerakumar

**Comment by SnehaVeerakumar** [comment]
I guess someone is working on that part of the issue. Find details in discord channel please.

**Comment by rohank2502** [comment]
> I guess someone is working on that part of the issue. Find details in discord channel please.

Ok will do

**Comment by himanshu007-creator** [comment]
done
