### ISSUE TITLE
Events Page

### ISSUE THREAD

**Issue by sheetalj2205** [himanshu007-creator/SFC-foundations#18]
All the events are not properly placed on the events page. It is hard for the reader to read them and they are not placed with proper paddings and space. We can use CSS grid, flex or bootstrap grid system for a better look. I would like to work on this issue for GSSOC'21.

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by himanshu007-creator** [comment]
Hi @sheetalj2205  , @chehak123 , please have a look here #12

**Comment by medhavi11** [comment]
I would like to work on this issue, I am GSSOC 2021 participant.

**Comment by himanshu007-creator** [comment]
@sheetalj2205  yes you can work on it. We just need an idea like how you will proceed. As we are redesigning everything so everything will be changes and so will the site structure. We just need to know how you are going to implement it. Prepare a prototype of code and send it within this week. Best of luck!

**Comment by shairanshrawat** [comment]
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same.
I thought of doing the following 
- At the start of the event page thought of using a Carousel where we can 4-5 picture from the event and writing quotes on that 
-  after that, using  Bootstrap’s cards for event detailing and placing them on the page using  CSS grid, flex, or bootstrap grid system for the upcoming and previous event
- having a hovering effect for more details 
- adding pagination 
- and adding a footer in the end

**Comment by himanshu007-creator** [comment]
@shairanshrawat  talk is over-rated, show us the code😉

**Comment by shairanshrawat** [comment]
> @shairanshrawat talk is over-rated, show us the code😉

@himanshu007-creator thanks for assigning
