### ISSUE TITLE
GSSoC'21: Add contact section in home page

### ISSUE THREAD

**Issue by shruti-mayank** [himanshu007-creator/SFC-foundations#182]
Referring to the nav-links, the contact section is not mentioned and present on the homepage of the website. I request the creators to assign me the issue.

**Comment by atharva21-stack** [comment]
Can I solve this issue?

**Comment by ApekshaAgarwal** [comment]
@himanshu007-creator please assign this issue to me. I would like to work on this.

**Comment by himanshu007-creator** [comment]
https://himanshu007-creator.github.io/SFC-foundations/pages/Contact-Us/contact.html

already there
