### ISSUE TITLE
CREATING MOCKUPS OF DIFFERENT PAGES.

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#183]
To make it easier for participants, we are planning to have a document containing mockup and description of various pages in website. This requires some time. I will have a meeting/call with the participant, explain every proposed view in detail  and within 3 days, participant have to make a document in specified manner.

**Comment by rohank2502** [comment]
I will  do this one  👍🏻

**Comment by codebuzzer01** [comment]
hey @himanshu007-creator  if someone hasn't contributed yet pls assign it to me.

**Comment by rohank2502** [comment]
> hey @himanshu007-creator if someone hasn't contributed yet pls assign it to me.

Sorry I am working on this !

**Comment by rohank2502** [comment]
@himanshu007-creator  Please remove Up for grab and assign to me

**Comment by rohank2502** [comment]
https://docs.google.com/document/d/1E3aV5X734KouT0YgulOxgdj9zATI2XEKneT_lPp2GGs/edit?usp=sharing 

In this Documents I have added Mockup Images of our pages Which are ready in code also just will give PR one by one so we can check them properly Now there is ABout Us section ready and events page ready I am going to create separate event pages for each event as on our old website . I will be creating all pages by myself as many of them are done already please don't assign anyone page creation

**Comment by rohank2502** [comment]
@SnehaVeerakumar Please review the design in docs file

**Comment by SnehaVeerakumar** [comment]
> @SnehaVeerakumar Please review the design in docs file

"More events" can be placed somewhere near the title as it may go missing if it is in bottom.

**Comment by rohank2502** [comment]
> > @SnehaVeerakumar Please review the design in docs file
> 
> "More events" can be placed somewhere near the title as it may go missing if it is at the bottom.

we have just 2 events in the upcoming how can we place more events before showing those two?

**Comment by SnehaVeerakumar** [comment]
> > > @SnehaVeerakumar Please review the design in docs file
> > 
> > 
> > "More events" can be placed somewhere near the title as it may go missing if it is at the bottom.
> 
> we have just 2 events in the upcoming how can we place more events before showing those two?

what is your suggestion about that ?

**Comment by rohank2502** [comment]
Please have a look at Design of Founder Page and suggest changes @SnehaVeerakumar

**Comment by SnehaVeerakumar** [comment]
> Please have a look at Design of Founder Page and suggest changes @SnehaVeerakumar

I am not the reviewer of this project. Stop tagging me everywhere😅

**Comment by himanshu007-creator** [comment]
> > Please have a look at Design of Founder Page and suggest changes @SnehaVeerakumar
> 
> I am not the reviewer of this project. Stop tagging me everywhere😅

All contributors are reviewers automatically, you CAN review ✔

**Comment by SnehaVeerakumar** [comment]
> > > Please have a look at Design of Founder Page and suggest changes @SnehaVeerakumar
> > 
> > 
> > I am not the reviewer of this project. Stop tagging me everywhere😅
> 
> All contributors are reviewers automatically, you CAN review ✔

Oh i was not aware about that. But still @rohank2502 kindly stop tagging me anywhere in this project 😅😅

**Comment by rohank2502** [comment]
> > > > Please have a look at Design of Founder Page and suggest changes @SnehaVeerakumar
> > > 
> > > 
> > > I am not the reviewer of this project. Stop tagging me everywhere😅
> > 
> > 
> > All contributors are reviewers automatically, you CAN review ✔
> 
> Oh i was not aware about that. But still @rohank2502 kindly stop tagging me anywhere in this project 😅😅

@himanshu007-creator  Told me to take suggestion from you regarding designs

**Comment by SnehaVeerakumar** [comment]
> > > > > Please have a look at Design of Founder Page and suggest changes @SnehaVeerakumar
> > > > 
> > > > 
> > > > I am not the reviewer of this project. Stop tagging me everywhere😅
> > > 
> > > 
> > > All contributors are reviewers automatically, you CAN review ✔
> > 
> > 
> > Oh i was not aware about that. But still @rohank2502 kindly stop tagging me anywhere in this project 😅😅
> 
> @himanshu007-creator Told me to take suggestion from you regarding designs

Oh maybe not from now,  sorry.

**Comment by rohank2502** [comment]
> > > > > > Please have a look at Design of Founder Page and suggest changes @SnehaVeerakumar
> > > > > 
> > > > > 
> > > > > I am not the reviewer of this project. Stop tagging me everywhere😅
> > > > 
> > > > 
> > > > All contributors are reviewers automatically, you CAN review ✔
> > > 
> > > 
> > > Oh i was not aware about that. But still @rohank2502 kindly stop tagging me anywhere in this project 😅😅
> > 
> > 
> > @himanshu007-creator Told me to take suggestion from you regarding designs
> 
> Oh maybe not from now, sorry.

ok Thanks for your help
