### ISSUE TITLE
I want to add no.of forks, issues, stars in the readme file .

### ISSUE THREAD

**Issue by srisatya1197** [himanshu007-creator/SFC-foundations#184]
I want to add no.of forks, issues, stars in the readme fie.
Example:
![ss5](https://user-images.githubusercontent.com/78905067/115119206-cc01ab80-9fc4-11eb-8d1d-00e5cb7bd81c.png)
I want to work on this . Please assign me this issue.

**Comment by rohank2502** [comment]
Will look good Can we let him done @himanshu007-creator  I think it's better to add that

**Comment by rohank2502** [comment]
@srisatya1197 please be specific what things will you add

**Comment by himanshu007-creator** [comment]
> I want to add no.of forks, issues, stars in the readme fie.
> Example:
> ![ss5](https://user-images.githubusercontent.com/78905067/115119206-cc01ab80-9fc4-11eb-8d1d-00e5cb7bd81c.png)
> I want to work on this . Please assign me this issue.

You can add other badges, ask @rohank2502  for more references

**Comment by rohank2502** [comment]
Share your idea on Discord channel we will have discussion and final it till morning 👍🏻

**Comment by srisatya1197** [comment]
@himanshu007-creator Thank you for assigning.
@rohank2502 What discussion you are referring to?
