### ISSUE TITLE
The feed image in the bottom is overlapping the content in the mobile view

### ISSUE THREAD

**Issue by gnikita432** [himanshu007-creator/SFC-foundations#185]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

- The feed image which in in fixed position in bottom is overlapping the other content of site in mobile view
## **Possible solution**

- Describe the solution you thought of.
I can remove that image for the mobile view only or
can make the size of image small 
or can add some feature like that image will be only visible on hovering on the number icon (190)in the bottom (only in mobile view)

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/61223163/115132631-87572e00-a01f-11eb-8875-c06d024b87ae.png)

**Comment by rohank2502** [comment]
Yes @gnikita432  I am working on this

**Comment by gnikita432** [comment]
Ohh Okay I am sorry for opening a duplicate issue.
Closing this issue.

**Comment by rohank2502** [comment]
> Ohh Okay I am sorry for opening a duplicate issue.
> Closing this issue.

Is ok you can find a new one thanks for contribution
