### ISSUE TITLE
Redesign About Us section

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#201]
## Issue Type:
[  ] Bug Report 
[ x]  Feature Request 
[  ] Documentaion

## **Describe the bug**

Redesign of About section as per old website 

When we click about us in navbar we will be directed to this section on the main page and from that section, we can navigate to different pages as we have in our old website rather than giving a drop down I think this will be an attractive approach 

![Screenshot 2021-04-21 135458](https://user-images.githubusercontent.com/76584243/115521955-496d3a80-a2a9-11eb-95d2-d5ff26f07144.png)

**Comment by rohank2502** [comment]
@himanshu007-creator  Can we go for this ? After getting approval from you will work on different pages and will take reference from our old website please have a look once

**Comment by himanshu007-creator** [comment]
Proceed! @rohank2502

**Comment by rohank2502** [comment]
> Proceed! @rohank2502

Cool Thanks ! Creating a Pr
