### ISSUE TITLE
Adding a Wave

### ISSUE THREAD

**Issue by arpit456jain** [himanshu007-creator/SFC-foundations#202]
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

I would like to add a back to top button

**Comment by rohank2502** [comment]
@arpit456jain  Please explain what exactly you want to add

**Comment by arpit456jain** [comment]
> @arpit456jain Please explain what exactly you want to add

Its like a arrow pointing upward and it will be visible when we scroll down and on clicking on that Arrow we will automatically reach to top

**Comment by rohank2502** [comment]
> > @arpit456jain Please explain what exactly you want to add
> 
> @rohank2502 Its like an arrow pointing upward and it will be visible when we scroll down and on clicking on that Arrow we will automatically reach the top

Actually, your  idea is good but we have a navbar which remains on top in any part of the website So I don't think its required but the final call will be taken by @himanshu007-creator

**Comment by arpit456jain** [comment]
I have also tried to add a wave and its looking like this
<img width="960" alt="wave2" src="https://user-images.githubusercontent.com/55352601/115556917-d24a9d00-a2ce-11eb-8cdf-119f9248a648.png">

**Comment by arpit456jain** [comment]
@rohank2502 @himanshu007-creator how about this wave feature ?

**Comment by rohank2502** [comment]
> @rohank2502 @himanshu007-creator how about this wave feature ?

I cant decide @himanshu007-creator will take final call

**Comment by himanshu007-creator** [comment]
> I have also tried to add a wave and its looking like this
> <img alt="wave2" width="960" src="https://user-images.githubusercontent.com/55352601/115556917-d24a9d00-a2ce-11eb-8cdf-119f9248a648.png">

can you share a GitHub page after deploying your proposed additions?
1) wave pattern 
2) back to top button.

additional comments:- try to implement 2nd feature in a effective method, so as the dogs image and counter is not effected.

**Comment by arpit456jain** [comment]
https://arpit456jain.github.io/coursera/

**Comment by rohank2502** [comment]
> https://arpit456jain.github.io/coursera/

Please Update your branch from master

**Comment by arpit456jain** [comment]
> > https://arpit456jain.github.io/coursera/
> 
> Please Update your branch from master

done @rohank2502 @himanshu007-creator
