### ISSUE TITLE
Need to create a SiteMap

### ISSUE THREAD

**Issue by chaitanyashimpi** [himanshu007-creator/SFC-foundations#21]
I saw your website, it's fabulous. And as it is big, it should have the SiteMap. 

I will make a sitemap.xml and sitemap.html for the website.

**Comment by chaitanyashimpi** [comment]
Can you please assign this issue to me as a part of GSSOC.

**Comment by himanshu007-creator** [comment]
@chaitanyashimpi  yes you can work on it. We just need an idea like how you will proceed. As we are redisigning everything so everything will be changes and so will the site structure. We just need to know how you are going to implement it. Prepare a prototype of code and send it within this week. Best of luck!

**Comment by chaitanyashimpi** [comment]
@himanshu007-creator @divyashukla23 I have made a Pull request, check it out. And I have tried my best to explain the process of how you can update it in the future.

**Comment by divyashukla23** [comment]
@chaitanyashimpi i will check it and update soon.

**Comment by himanshu007-creator** [comment]
@chaitanyashimpi , please wait for some time. Sitemap will be meaningful once the frontend work is over. Then you can help yourself and send a new PR

**Comment by rohank2502** [comment]
Same issue as  #262  !  @himanshu007-creator
