### ISSUE TITLE
Responsive footer

### ISSUE THREAD

**Issue by gnikita432** [himanshu007-creator/SFC-foundations#212]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

-The footer is not responsive for all devices. Hers the how its look in iPad
![image](https://user-images.githubusercontent.com/61223163/115713303-785fdb00-a393-11eb-9cac-4d044e42921b.png)

## **Possible solution**

- Footer content should be aligned properly in other than desktop view

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by rohank2502** [comment]
Hey Thanks for creating issue but that's our old website on Wordpress new website you have to see by deploying your version

**Comment by himanshu007-creator** [comment]
hi @gnikita432  we are working on a new website whose test version can be seen <a href="https://himanshu007-creator.github.io/SFC-foundations/#events">here</a> new pages are being created one by one. If you find another issue/suggestion , you are most welcome. Maybe you can send a PR as well🙂

**Comment by gnikita432** [comment]
Ohh Okay sorry for inconvenience.
