### ISSUE TITLE
Create Founder Page 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#215]
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

Please suggest If changes in this design happy to make changes if they will enhance looks 

![founder](https://user-images.githubusercontent.com/76584243/115844474-7ce0ce00-a43d-11eb-8d6f-f2003c6a08b7.png)

**Comment by rohank2502** [comment]
@divyashukla23 @himanshu007-creator  Suggest changes in design as you get time

**Comment by himanshu007-creator** [comment]
yes, i wanted there to be a dropdown below it for more information
structure
<table>
<tr><td>Picture of Founder</td></tr>
<tr><td>Name ( large and caital)</td></tr>
<tr><td>Designation ( a bit small than name, color gray and text in italics</td></tr>
<tr><td>Dropdown button for about (bio) section with the label **KNOW MORE**</td></tr>
</table>

**Comment by rohank2502** [comment]
> yes, i wanted there to be a dropdown below it for more information
> structure
> 
> Picture of Founder
> Name ( large and caital)
> Designation ( a bit small than name, color gray and text in italics
> Dropdown button for about (bio) section with the label **KNOW MORE**

OK means after clicking know more the text will be displayed right

**Comment by himanshu007-creator** [comment]
> > yes, i wanted there to be a dropdown below it for more information
> > structure
> > Picture of Founder
> > Name ( large and caital)
> > Designation ( a bit small than name, color gray and text in italics
> > Dropdown button for about (bio) section with the label **KNOW MORE**
> 
> OK means after clicking know more the text will be displayed right

Yes

**Comment by rohank2502** [comment]
Have done the changes please have a look @himanshu007-creator
