### ISSUE TITLE
Create Page Core team 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#218]
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

**Comment by rohank2502** [comment]
@himanshu007-creator  Please have a look at this video the working of core team page suggest changes if any 
https://drive.google.com/file/d/1pmwqrlWupcoPZptGJGkxffacA4YDd6fn/view?usp=sharing

**Comment by himanshu007-creator** [comment]
done
