### ISSUE TITLE
Dark/Light mode

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [himanshu007-creator/SFC-foundations#223]
I want to add dark/light mode to the website.

[GSSOC'21]

Please assign me this issue @himanshu007-creator

**Comment by rohank2502** [comment]
Sorry We have Dark/Light mode @Bhavya-Sehgal  Thanks for showing interest in contribution you can definitely find any other issue to work on

**Comment by rohank2502** [comment]
@Bhavya-Sehgal  Please close the issue
