### ISSUE TITLE
Donate Page

### ISSUE THREAD

**Issue by nidhivanjare** [himanshu007-creator/SFC-foundations#224]
## Issue Type:
- [ ] Bug Report 
- [x]  Feature Request 
- [ ] Documentaion

## **Describe the bug**

- Create a donate page

## **Possible solution**

- I would like to create a donate page for the foundation if you provide me the relevant details. 

## **Screenshots**

<img width="886" alt="image" src="https://user-images.githubusercontent.com/55665104/116064768-f4179b80-a6a3-11eb-8874-e70593a42323.png">

**Comment by nidhivanjare** [comment]
@himanshu007-creator can I work on this?

**Comment by divyashukla23** [comment]
@nidhivanjare go ahead with the work and send a PR. I will add a label to this issue

**Comment by nidhivanjare** [comment]
I have some questions.

For the donation page, I have to add a payment method, and for that, I would have to add PHP on the side.
Is that okay?
And are there any other requirements for the page?

**Comment by rohank2502** [comment]
> I have some questions.
> 
> For the donation page, I have to add a payment method, and for that, I would have to add PHP on the side.
> Is that okay?
> And are there any other requirements for the page?
> 
> @divyashukla23

@himanshu007-creator  Please have a look here! We need to talk with Backend person for this because he is handling the whole backend so this will be helpful

**Comment by divyashukla23** [comment]
@nidhivanjare Design the front end of the donate page and send PR , do not integrate the payment gateway that will be handles by the person working on backend.

**Comment by himanshu007-creator** [comment]
@nidhivanjare  we won't be using PHP in backend, we will be using django only. It will be for updating/adding/subtracting new blogs and articles.
My suggestion to you will be making a separate page having good pictures + persive text . We would really appreciate your contributions and looking forward to it real soon.
Best of luck🎉

**Comment by nidhivanjare** [comment]
okay understood !!
Thank You !!

**Comment by rohank2502** [comment]
> okay understood !!
> Thank You !!

If need help in frontend please let me know will be happy to help !

**Comment by nidhivanjare** [comment]
I have created the PR. Let me know if there are any changes. 
@rohank2502. @himanshu007-creator
