### ISSUE TITLE
Bug in Backend

### ISSUE THREAD

**Issue by arpit456jain** [himanshu007-creator/SFC-foundations#225]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**
Urls are not correct in navbar when user is on any different page other than home page we are not able to go to 

about 
project 
news and etc pages

## **Possible solution**
It should redirect to home page  and then to the particular section

## **Screenshots**

https://user-images.githubusercontent.com/55352601/116085426-6eecb080-a6bc-11eb-8442-15cc2c788b42.mp4

.

**Comment by arpit456jain** [comment]
@himanshu007-creator can i start working

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator can i start working

Hi @arpit456jain , currently some pages are under development. Till this month, work will be over, that's why we have placed hyperlink reference to "#"

**Comment by arpit456jain** [comment]
Ok

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator you are getting me wrong actually
> Lets say there is an about section on home page in navbar its given #about it will work fine on home page but when we are on any other page that will not work .
> 
> For proper working of that kind of urls we have to right
> 
> /#about means first go to Home page and then about section

Oh , my bad, i completely understand what you are referring to now. Thing is, first we need to get whole code of frontend done, these minor changes can be made later on. Hope you get what im saying

**Comment by arpit456jain** [comment]
yes 
no problem
