### ISSUE TITLE
Backend for Contact Us

### ISSUE THREAD

**Issue by arpit456jain** [himanshu007-creator/SFC-foundations#226]
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

I would like to add backend code for contact us . for now as we know there is no such page for contact us but i can make form on blank page and write the backend .
when the contact page will be added we can simply change the url

**Comment by rohank2502** [comment]
@himanshu007-creator  Do we need backend or just some API will do our work I am working on it will give you results in 2-3 days hope its fine

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Do we need backend or just some API will do our work I am working on it will give you results in 2-3 days hope its fine

An API would do just fine!
Hope to see a good result

**Comment by rohank2502** [comment]
> > @himanshu007-creator Do we need backend or just some API will do our work I am working on it will give you results in 2-3 days hope its fine
> 
> An API would do just fine!
> Hope to see a good result

Yes For Sure
