### ISSUE TITLE
Back on top functionality for webpage

### ISSUE THREAD

**Issue by shreyasZ10** [himanshu007-creator/SFC-foundations#227]
## Issue Type:
[  ]  Feature Request 

## **Describe the bug**

- Add back on top functionality for the webpage.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by rohank2502** [comment]
Hello @shreyasZ10  We have Navigation Bar on every section of Page  So It will not be as such  useful to apply a button to came back  on top Thanks for Contribution ! Please find another issue or If you think its required please let me know in which page and in which section Please help us in improvement this will matter us a lot
