### ISSUE TITLE
Contact Us Page 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#228]
Hello, Everyone, We have to check the working of the Contact Us page so need your help! 

The link for Contact us page is given below please fill It We want to know how the information is received at our end I will attach the ss of received Emails. After this testing we will look on Css @himanshu007-creator  Happy to make  changes so please test working of form and do suggest the changes  ! 

This will Email to my id because its registered will tell PA to make required changes and creating account managing keys etc !

**Comment by rohank2502** [comment]
https://rohank2502.github.io/SFC-foundations/pages/Contact-Us/contact.html   This is link of form @himanshu007-creator @divyashukla23

**Comment by rohank2502** [comment]
![Screenshot 2021-04-28 170220](https://user-images.githubusercontent.com/76584243/116396850-78eceb80-a843-11eb-84f8-c9343f86a4cb.png)

Got this Email After filling Form

**Comment by himanshu007-creator** [comment]
@rohank2502 , functionality nis cool, I hope there are no call limits for API and it's free. Now you can improve upon the visualisation, form looks GTG, but background can be made better. Some gradient, wave or anything you like. But keep it simple, just a pinch of styling will do the job.

**Comment by rohank2502** [comment]
> @rohank2502 , functionality nis cool, I hope there are no call limits for API and it's free. Now you can improve upon the visualisation, form looks GTG, but the background can be made better. Some gradient, wave or anything you like. But keep it simple, just a pinch of styling will do the job.

We have a monthly limit of 50 responses! https://formspree.io/plans  Please have a look at prices here! I think this is the best opinion which we can take !! And we are also provided a dashboard where we get an overview of how many emails we received and from whom! I don't think there will be any better free platform for this service!

**Comment by rohank2502** [comment]
> @rohank2502 , functionality nis cool, I hope there are no call limits for API and it's free. Now you can improve upon the visualisation, form looks GTG, but background can be made better. Some gradient, wave or anything you like. But keep it simple, just a pinch of styling will do the job.

Shall we continue then ? If you this the per month 50 is enough

**Comment by himanshu007-creator** [comment]
Yes , continue!

**Comment by rohank2502** [comment]
> Yes , continue!

OK, Please let me know what change from your side will you like to see! SO I can make those changes for sure and also try to make something from my end to add some more attractive look !!

**Comment by himanshu007-creator** [comment]
First try to create a good background image that suits the cause NGO stands for. above that place the form. For form, you cab take inspiration from apple UI, create a water translucent effect ( glassmorphism). take form structure idea from <a href="https://www.youtube.com/watch?v=-sMXE7E3R3M">here</a> and form glass effect can be taken from <a href="https://glassmorphism.com/">here</a>
rest i hope you are a creative person😉
