### ISSUE TITLE
Animation to Projects Section

### ISSUE THREAD

**Issue by Dwitrisha** [himanshu007-creator/SFC-foundations#23]
I want to add animations to the projects section on the home page using js. @divyashukla23 @himanshu007-creator @praveenscience can you assign this issue to me?

**Comment by himanshu007-creator** [comment]
> I want to add animations to the projects section on the home page using js. @divyashukla23 @himanshu007-creator @praveenscience can you assign this issue to me?

Hi! Can you please elaborate your proposal?

**Comment by Dwitrisha** [comment]
I want to add some animations on the projects sections such as hover effect or so

**Comment by himanshu007-creator** [comment]
This issue is not having a larger scope so closing it.
