### ISSUE TITLE
Photo not linked

### ISSUE THREAD

**Issue by bug-debug-done** [himanshu007-creator/SFC-foundations#234]
Some photos above footer section are not linked
![Screenshot from 2021-05-01 20-59-00](https://user-images.githubusercontent.com/75927761/116787163-3f74e400-aac0-11eb-9f5f-c1b31561d046.png)

**Comment by bug-debug-done** [comment]
@himanshu007-creator  please have a look at this

**Comment by rohank2502** [comment]
Yes @bug-debug-done  the work is under process !!

**Comment by Anubhav-developr** [comment]
well i can fix this, just tell which photos you want
