### ISSUE TITLE
Include Python and Django badges in TECH stack ( README )

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#235]
GO GET IT!

**Comment by rohank2502** [comment]
@kavyashree2001 hey will like to work on this ?

**Comment by kavyashree2001** [comment]
@himanshu007-creator  I would like to work on this issue...please assign me this issue!

**Comment by rohank2502** [comment]
Great @kavyashree2001  I will like to  help  you in this !! 
Those batches are added from https://github.com/Ileriayo/markdown-badges This repository !! You have to add  the links of Python and Django as told by @himanshu007-creator  !! in read me file !! Please let me know if you need any help !!

**Comment by kavyashree2001** [comment]
> Great @kavyashree2001  I will like to  help  you in this !! 
> Those batches are added from https://github.com/Ileriayo/markdown-badges This repository !! You have to add  the links of Python and Django as told by @himanshu007-creator  !! in read me file !! Please let me know if you need any help !!

Yeah sure!

**Comment by himanshu007-creator** [comment]
@kavyashree2001 , umm it appears , you created a PR to self. You just created a PR to YOUR master branch. Thats no the way, 
What you need to do now?
1) in your forked repo, open the <code>include-badges </code> branch
2) click on compare, make sure the following:-
Base repository  = <code>himanshu007-creator/SFC-foundations</code>
base= <code>master</code>
head repository = <code>kavyashree/SFC-foundations</code>
compare = <code>include-badges</code>
 Ahter checking all four, create the PR, in  description  type <code>Resolves #235</code>
