### ISSUE TITLE
Https binding is safer

### ISSUE THREAD

**Issue by Anubhav-developr** [himanshu007-creator/SFC-foundations#236]
**Web config needed as it is doing payments too , so https will be secure , and this can be achieved by ssl certificate**
![Screenshot 2021-05-03 191144](https://user-images.githubusercontent.com/71844334/116885458-87714380-ac45-11eb-9900-67732f8679be.jpg)

**Comment by rohank2502** [comment]
Hey, @Anubhav-developr  you are looking at our Old website !!

**Comment by rohank2502** [comment]
@himanshu007-creator  Can we close this issue because this is showing a bug in our old site!

**Comment by himanshu007-creator** [comment]
@Anubhav-developr , as @rohank2502  have correctly mentioned, you are looking at the old website. New one is under development and after its done, we will be securing the domain with a SSL

**Comment by Anubhav-developr** [comment]
ok
