### ISSUE TITLE
Resizing of the image and context in project area.

### ISSUE THREAD

**Issue by Rutikab12** [himanshu007-creator/SFC-foundations#238]
## Issue Type:

There is resizing of the image needed in the project area.

## **Possible solution**

- I will fix this as GSSoC'21 participant. If Creator wants to improve it.

**Comment by himanshu007-creator** [comment]
@Rutikab12 please attach screenshots and a brief description of issue

**Comment by Rutikab12** [comment]
![Screenshot (431)](https://user-images.githubusercontent.com/71027989/116995785-20609700-acf8-11eb-8eb2-76cdd593b5ab.png)


In the project area, the heading of the 2nd and 3rd image looks a little bit inappropriate, and the image is also not in the proper size for the third mission. So I want to improve that.

**Comment by rohank2502** [comment]
> ![Screenshot (431)](https://user-images.githubusercontent.com/71027989/116995785-20609700-acf8-11eb-8eb2-76cdd593b5ab.png)
> 
> In the project area, the heading of the 2nd and 3rd image looks a little bit inappropriate, and the image is also not in the proper size for the third mission. So I want to improve that.

I think @himanshu007-creator is an old website !!

**Comment by himanshu007-creator** [comment]
its the old website. Sorry
