### ISSUE TITLE
Suggestion: Use of a suitable background

### ISSUE THREAD

**Issue by satcasm** [himanshu007-creator/SFC-foundations#24]
When I visited the home page, it gives me restless feeling if I see some texts overlapping , I mean certainly it's not a big issue , but surely it would be look great if we change the background to something that doesn't result in overlapping texts.
**Screenshot:**
![image](https://user-images.githubusercontent.com/56315878/110358205-26245e00-8062-11eb-8bbb-2da5c927bd73.png)

Would like to work on in it if seemed suitable under GSSOC' 21.

**Comment by Aanchal116** [comment]
Hii , I would like to work on this issue as a part of GSSOC'21. I've hands-on practice in web development and also a mentorship experience. Please assign this task to me if possible.

**Comment by himanshu007-creator** [comment]
@satcasm  create a template and send pr

**Comment by satcasm** [comment]
@himanshu007-creator  what did you meant by template? I was thinking of using some css to adjust the image position , so that the overlapping wouldn't be there.

**Comment by himanshu007-creator** [comment]
old website issue
