### ISSUE TITLE
New Our team section created

### ISSUE THREAD

**Issue by arpit456jain** [himanshu007-creator/SFC-foundations#240]
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

I have created a new section for out teams on home page have a look
https://arpit456jain.github.io/coursera/index.html

**Comment by rohank2502** [comment]
@arpit456jain  Actually we have created Different pages for the team section @himanshu007-creator told me how they want and  I am working on it !!

**Comment by himanshu007-creator** [comment]
@arpit456jain  this issue is being worked upon, but keep the work for now, will use it somewhere else

**Comment by arpit456jain** [comment]
ok
