### ISSUE TITLE
Site suggestions

### ISSUE THREAD

**Issue by atharva21-stack** [himanshu007-creator/SFC-foundations#243]
## Issue Type:
[x] Bug Report 
[x]  Feature Request 
[  ] Documentation

## **Describe the bug**

1. The Logo on the Header of the website  is not aligned properly , hence the top navigation bar is huge in height.
2.  Not all project images are aligned properly on home page.
3. Move social profiles to Footer.
4. Use Fontawesome for social profiles.

## **Possible solution**

1. We can rearrange the logo and the title to look and feel better.
2. Custom CSS can be developed and added to align images and make all images of same size.

**Comment by atharva21-stack** [comment]
I would like to work on these issues @himanshu007-creator .

**Comment by rohank2502** [comment]
@atharva21-stack  Please add screen shots!

**Comment by rohank2502** [comment]
@himanshu007-creator  Can we close this I think he was asking for the old site !
