### ISSUE TITLE
Clean Index.html , script.js , style.css 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#247]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

Will clean the 3 files of the index page and this will help us to maintain the code and also read the code easily for the third person !!

**Comment by Anuradha0501** [comment]
I would like to work on this issue as a GSSOC'21 participant.

**Comment by rohank2502** [comment]
We will do this after updating content or might be simultaneous! Sorry !!
