### ISSUE TITLE
Search bar 

### ISSUE THREAD

**Issue by meghna750** [himanshu007-creator/SFC-foundations#25]
This website has many events listed, and in future, the count will surely increase. The same is the case with the blogs section.
I want to add a search bar for both the events section and blogs section (as a part of GSSOC'21 participant). Please assign this task to me.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue. Could you please assign it to me?

Thanks!!

**Comment by himanshu007-creator** [comment]
sorted
