### ISSUE TITLE
Back to Top Button

### ISSUE THREAD

**Issue by shrishti-c** [himanshu007-creator/SFC-foundations#250]
I'd like to add back to Top button in website.

**Comment by Elizah550** [comment]
I have good experience with UI and I can clear this issue in 3-4 hrs of time please assign it to me.

**Comment by himanshu007-creator** [comment]
@Elizah550 , you can work on this issue, but please view the present website. You can find it in readme/ github pages link, then think of innovating this feature

**Comment by rohank2502** [comment]
@Elizah550  Please let us know the work progress till today ! @himanshu007-creator  If he/she fails to reply Can I take over this because it's more than 3 days you have assigned !

**Comment by himanshu007-creator** [comment]
> @Elizah550 Please let us know the work progress till today ! @himanshu007-creator If he/she fails to reply Can I take over this because it's more than 3 days you have assigned !

yeah, i will wait till 2 p.m for a reply, otherwise its yours

**Comment by rohank2502** [comment]
Please assign this to me @himanshu007-creator

**Comment by adysis14** [comment]
Hey! I'm interested in solving this issue . I would be very grateful if you assign this issue to me under GSSOC'21

Thank You!

**Comment by rohank2502** [comment]
> 
> 
> Hey! I'm interested in solving this issue . I would be very grateful if you assign this issue to me under GSSOC'21
> 
> Thank You!

Great !! Sorry but I am working on this issue !
