### ISSUE TITLE
Enhance some details

### ISSUE THREAD

**Issue by Saumya-07** [himanshu007-creator/SFC-foundations#254]
## Issue Type:
 Feature Request 

1. In the project section, the images and blocks are not aligned.
I can align them so that it looks better.
2. The social media links can be brought in the center and can be more styled (like on hover it shows different color for each icon and shows social media name )

## **Screenshots**
![Screenshot (572)_LI](https://user-images.githubusercontent.com/68998355/117581495-a88cd500-b11a-11eb-86e4-365c2736e043.jpg)

![Screenshot (573)_LI](https://user-images.githubusercontent.com/68998355/117581552-ff92aa00-b11a-11eb-90d7-f6a488fbd5e2.jpg)

I am a GSSOC'21 participant and would like to work on this issue.
please assign this issue to me if you find it valid.

**Comment by himanshu007-creator** [comment]
Hi @Saumya-07 , sorry to break the news, but you are referring to old website. The new website does not have similar issues.
