### ISSUE TITLE
Top button is not user friendly #GsSoc'21

### ISSUE THREAD

**Issue by kanishka8276** [himanshu007-creator/SFC-foundations#26]
It would be better if there is top written or an arrow on the button.
Please assign this to me.

**Comment by Aanchal116** [comment]
Hii Sir , 
I would like to work on this issue as a part of GSSOC'21. I've hands-on practice in web development and also a mentorship experience. Please assign this task to me if possible.

**Comment by innovation-platform** [comment]
I would like to work on this issue as part of GSSoc'21
