### ISSUE TITLE
Code Architechture

### ISSUE THREAD

**Issue by PandeySomya77** [himanshu007-creator/SFC-foundations#262]
Can I add code architechture in readme file.

**Comment by himanshu007-creator** [comment]
hi @PandeySomya77 , can you explain your solution a little bit more?

**Comment by rohank2502** [comment]
@PandeySomya77  Hey !! We are glad you show interest in contribution !! Will you like to explain more what exactly will you like to add in code architecture

**Comment by PandeySomya77** [comment]
Yes sure, I want thinking to add a code architechture in the readme file so that it is readable to everyone.
![architwc](https://user-images.githubusercontent.com/43266956/118032453-54395d80-b385-11eb-8b1a-bda8fca974d3.png)

**Comment by rohank2502** [comment]
@himanshu007-creator  I think this will be great for the new developer !

**Comment by himanshu007-creator** [comment]
@PandeySomya77  HI, you van work on this issue, but the thing is you have to wait. For now you can draw a similar architecture for Main branch. but we also have a Backend , that contains whole Backend Django code. So once we integrate it. Then this will be useful

**Comment by rohank2502** [comment]
> 
> 
> @PandeySomya77 HI, you van work on this issue, but the thing is you have to wait. For now you can draw a similar architecture for Main branch. but we also have a Backend , that contains whole Backend Django code. So once we integrate it. Then this will be useful

We can go for two different that will be easy for new who have not worked on this project before

**Comment by himanshu007-creator** [comment]
> > @PandeySomya77 HI, you van work on this issue, but the thing is you have to wait. For now you can draw a similar architecture for Main branch. but we also have a Backend , that contains whole Backend Django code. So once we integrate it. Then this will be useful
> 
> We can go for two different that will be easy for new who have not worked on this project before

Umm okay, that is also another way @PandeySomya77 , you can proceed in following manner.

**Comment by rohank2502** [comment]
@PandeySomya77 Please let us know the work progress

**Comment by PandeySomya77** [comment]
It'll will be done by tomorrow.

**Comment by rohank2502** [comment]
> 
> 
> It'll will be done by tomorrow.

No Issues !!

**Comment by rohank2502** [comment]
@PandeySomya77  Any further update ?

**Comment by himanshu007-creator** [comment]
Will wait for tomorrow, otherwise removing assignment

**Comment by Sarthakjain594** [comment]
heyy , 
Can I add this project architecture ??

**Comment by himanshu007-creator** [comment]
> heyy ,
> Can I add this project architecture ??

Hi! Yeah sure , but can you make it look like  <a href="https://github.com/himanshu007-creator/SFC-foundations/issues/262#issuecomment-840036974">this</a>?

**Comment by Sarthakjain594** [comment]
ya I can make it  look like this tree structure , but I think the background is black due to dark mode . Isn't it ??

**Comment by himanshu007-creator** [comment]
> ya I can make it look like this tree structure , but I think the background is black due to dark mode . Isn't it ??

no, we want it to have dark background. Means it have black background no matter what's user's selected theme.🙂

**Comment by Sarthakjain594** [comment]
ohh , Ok Let me try to make it black background
