### ISSUE TITLE
Changed Feed Styling ! 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#268]
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

https://rohank2502.github.io/SFC-foundations/

Added only to index page !! 👍🏻

**Comment by himanshu007-creator** [comment]
> ## Issue Type:
> [ ] Bug Report
> [x] Feature Request
> [ ] Documentaion
> 
> https://rohank2502.github.io/SFC-foundations/
> 
> Added only to index page !! 👍🏻

It looks super cute!, just give circle some color, and make it mobile responsive

**Comment by rohank2502** [comment]
Hey !! @himanshu007-creator  Please have a look at the Changes !!

**Comment by himanshu007-creator** [comment]
COOL, SEND PR RIGHT AWAY :)
