### ISSUE TITLE
Provide GitHub pages link in README

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#271]
https://himanshu007-creator.github.io/SFC-foundations/

Insert this link in readme.md

display:-
-H1 tag- link <>

eg

<h1>GitHub Page Deployment can be found <a href="https://himanshu007-creator.github.io/SFC-foundations/">Here</a></h1>

**Comment by techpkd123** [comment]
@himanshu007-creator please assign the issue to me ? I am working on it.
