### ISSUE TITLE
Sticky Social Profile 

### ISSUE THREAD

**Issue by SamikshaSankar** [himanshu007-creator/SFC-foundations#274]
## Issue Type:
[  ] Bug Report 
[ Y ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

- I want to add social media slider

## **Possible solution**

- When user can scroll social media bar will be fixed

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by himanshu007-creator** [comment]
hi @SamikshaSankar , can you share some media (pictures/videos) supporting your idea.

**Comment by SamikshaSankar** [comment]
Uploading VID_20210516_145902.mp4…
...Like this

**Comment by himanshu007-creator** [comment]
> Uploading VID_20210516_145902.mp4…
> ...Like this

let it upload :)

**Comment by SamikshaSankar** [comment]
![IMG_20210516_193630](https://user-images.githubusercontent.com/52104082/118400160-120e6580-b67e-11eb-8bf0-f4a30dd7da66.jpg)
In that we can apply animation based on  transitions and transforms.

**Comment by himanshu007-creator** [comment]
umm,no, that is not needed, we aim to make a minimilistic website and all socials are already in contact us section

**Comment by himanshu007-creator** [comment]
@SamikshaSankar . still a big Thanks for your time :)
