### ISSUE TITLE
Enhancement  on Know SFC Page

### ISSUE THREAD

**Issue by PranavChauhan22** [himanshu007-creator/SFC-foundations#277]
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

## **Describe the feature**
Improvement of the Know SFC page

## **Possible solution**
I am going to add a new illustrator image developed using Adobe Illustartor placed at top right corner and text alignment and font will also be improved. Both the features will include animation and will be user interactive.

## **Screenshots**
N/A

**Comment by PranavChauhan22** [comment]
Admins please assign me this issue

**Comment by himanshu007-creator** [comment]
hi @PranavChauhan22 , can you elaborate a bit more about your suggestions? Try attaching some media (pics/videos) to support your work.

**Comment by rohank2502** [comment]
@PranavChauhan22  Any updates ? If any please let us know !!
