### ISSUE TITLE
Rebuilding the whole site using some appropriate framework and backend 

### ISSUE THREAD

**Issue by mridul-netizen** [himanshu007-creator/SFC-foundations#28]
The site is nothing but simple templates of wordpress ,it needs to be coded and made accordingly for use to add new blog posts and other new features

**Comment by nNikita1018** [comment]
I want to contribute in this project. by solving this issue.

**Comment by Aman1905** [comment]
Hey 
I guess we need to work on the whole website from the scratch and I would suggest we must use React as it is in demand now a days and also a great web framework to build sites. Do assign me this and I may help in rebuilding the website again

Thank You

**Comment by himanshu007-creator** [comment]
> The site is nothing but simple templates of wordpress ,it needs to be coded and made accordingly for use to add new blog posts and other new features

main concern is about simplicity of code + blog management. Can you do it alone? if yes, revert back asap @Aman1905  or @mridul-netizen
