### ISSUE TITLE
Fix all links in Nav-Bar

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#280]
Fix all the links in the navbar . Just go through different pages and replace all "#" references with their proper hyperlinks.

**Comment by rohank2502** [comment]
Hey, I will be working on this !  Will tell you few points we need to think on will discuss those

**Comment by rohank2502** [comment]
Suppose if we are on news page ( opened from more news ) and we clicked the about section we cant  get redirected to the about us  section on home . We can go to home page but we cant directly get navigated to about us

**Comment by himanshu007-creator** [comment]
i think there can be a way out for this, at present there is just 404

**Comment by rohank2502** [comment]
> 
> 
> i think there can be a way out for this, at present there is just 404

Yes that is because we have not added the links but I am saying different how to navigate to section in home page from other  page that I am saying

**Comment by himanshu007-creator** [comment]
> > i think there can be a way out for this, at present there is just 404
> 
> Yes that is because we have not added the links but I am saying different how to navigate to section in home page from other page that I am saying

yeah, i got your point, we can go to a page, but going to specific section of page, it require some work.

**Comment by himanshu007-creator** [comment]
@rohank2502 , there is one solution, we can use relative links in the homepage, and in other pages, we can use absolute links

for example in homepage 
about us:  href="#about"

in other pages
about us : href="https://himanshu007-creator.github.io/SFC-foundations/index.html#about"

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 , there is one solution, we can use relative links in the homepage, and in other pages, we can use absolute links
> 
> for example in homepage
> about us: href="#about"
> 
> in other pages
> about us : href="https://himanshu007-creator.github.io/SFC-foundations/index.html#about"

I Will give it  a  try
