### ISSUE TITLE
Alignment of cards in project session.

### ISSUE THREAD

**Issue by mansijain980** [himanshu007-creator/SFC-foundations#285]
[  ]  Feature Request 

## **Description**

![image](https://user-images.githubusercontent.com/63226239/118941552-7af02900-b96f-11eb-8c37-8622412e631c.png)
These cards should  also in proper order. Images should be of same sizes,

## **Possible solution**

Spacing in headings is not uniform in these three . "Read more " this should highlighted so that it will clearly visible and will click it to read more .

**Comment by himanshu007-creator** [comment]
Old website issue, new one can be found <a href="https://himanshu007-creator.github.io/SFC-foundations/">here</a>
