### ISSUE TITLE
Improved Footer

### ISSUE THREAD

**Issue by mansijain980** [himanshu007-creator/SFC-foundations#286]
![image](https://user-images.githubusercontent.com/63226239/118942676-94de3b80-b970-11eb-91a5-4ead536ba6a9.png)
These 3 names can be in list from top to bottom .After copyright . SFC foundation should be in next line.
.

**Comment by himanshu007-creator** [comment]
Old website issue, new one can be found <a href="https://himanshu007-creator.github.io/SFC-foundations/">here</a>
