### ISSUE TITLE
Explore Button on Home page 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#288]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

The Explore button on the home page is not getting redirected to anything we can add something in that or we can simply remove the button ! 

![Screenshot 2021-05-20 200451](https://user-images.githubusercontent.com/76584243/118999570-01c0f800-b9a8-11eb-952e-df34bf098d54.png)

**Comment by Maaz-Code** [comment]
I think we should use the button to redirect to the about us section !! @himanshu007-creator I can do that.

**Comment by rohank2502** [comment]
> 
> 
> I think we should use the button to redirect to the about us section !! @himanshu007-creator I can do that.

Sorry But I don't think so because we have dedicated button for about us section

**Comment by himanshu007-creator** [comment]
@Maaz-Code , your suggestion is right as a person who have just landed here. But @rohank2502  have been here for a long, so from his point of view, it's justified as well. I personally feel deleting this is a better option.
@Maaz-Code , I encourage you to find other issues to work on :)
@rohank2502 proceed as described in description.

**Comment by rohank2502** [comment]
Fixed in #289
