### ISSUE TITLE
Socials in Footer 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#292]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

The Social in the footer of the contact us page are different from the rest of the pages !  

Possible solution 
1. TO change the icon of the rest of the pages as contact us page
2. To change the icon of contact us page as other page

**Comment by rohank2502** [comment]
Please let me know what to  do @himanshu007-creator

**Comment by himanshu007-creator** [comment]
> Please let me know what to do @himanshu007-creator

Change icon of contact us page to those used in other pages
