### ISSUE TITLE
Blog management facility

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#3]
FEATURES NEEDES:-
admin can add articles along with pictures. I suggest to implement a template approach. like there will be a basic template that includes user defined number of images and below it goes the matter.
For reference om how articles should be uploaded, visit the <a href="http://sfcfoundations.com/category/blogs/">here</a>.

**Comment by ashi-sharma** [comment]
Can I work on this?

**Comment by himanshu007-creator** [comment]
> Can I work on this?

You can start refining your work, making it more efficient, gssoc will start from 1st March only.

**Comment by ashi-sharma** [comment]
@himanshu007-creator can u assign me this issue. I am working on this.

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator can u assign me this issue. I am working on this.

I will assign this issue on March 1 . Till then , get your code together. Best of luck.👍🏽

**Comment by himanshu007-creator** [comment]
Have a look here first of all https://github.com/himanshu007-creator/SFC-foundations/issues/12

**Comment by sneha-nitdgp** [comment]
Can you please assign this to me?

**Comment by mansijain980** [comment]
@himanshu007-creator sir , i can make a responsive blog template.
Assign this to me .

**Comment by himanshu007-creator** [comment]
@ashi-sharma 5  yes you can work on it. We just need an idea like how you will proceed. As we are redesigning everything so everything will be changes and so will the site structure. We just need to know how you are going to implement it. Prepare a prototype of code and send it within this week. Best of luck!

**Comment by ashi-sharma** [comment]
okay, I will be sharing the prototype soon.

**Comment by ashi-sharma** [comment]
@himanshu007-creator @divyashukla23  I have implemented the website(mainly the blog management part) using `embedded javascript templating(ejs)` . Other than that I have used `HTML`, `CSS`, `Bootstrap` for basic structure and styling. UI and design is to be improved in future according to the overall design and color of website(mainly homepage). 
Also I want to know how and where will be the feature of composing a blog will be added? For now I have added a link on top for developing basic functioning of site. Give some suggestions!


https://user-images.githubusercontent.com/57591881/111083180-380a7300-8532-11eb-9a7e-fbc2d0a293e9.mp4

**Comment by mansijain980** [comment]
@himanshu007-creator sir , I want to contribute on this issue as it seems very simple . I want to make it a lil bit attractive . 
Please assign it to me .

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator @divyashukla23 I have implemented the website(mainly the blog management part) using `embedded javascript templating(ejs)` . Other than that I have used `HTML`, `CSS`, `Bootstrap` for basic structure and styling. UI and design is to be improved in future according to the overall design and color of website(mainly homepage).
> Also I want to know how and where will be the feature of composing a blog will be added? For now I have added a link on top for developing basic functioning of site. Give some suggestions!
> 
>  SFC.Foundations.-.Google.Chrome.2021-03-15.01-56-55.mp4

HI @ashi-sharma , you should work to make another PR making an admin panel, where admin can login and he/she have rights to add /remove/ modify blogs

**Comment by SnehaVeerakumar** [comment]
Look into the link provided to know about my work for this project using django. https://drive.google.com/drive/folders/1TsQ0l-NGlhbgtonAMpDrwSRIcxGKLqVA?usp=sharing The landing page will be of your choice, I will just link frontend to my codebase. If the initial idea is fine, I can add more features such as providing an option to style the words in blog, uploading bluk images/videos, sending email to the admins and many more features. @himanshu007-creator  Please assign me the issue if you like my work.

**Comment by himanshu007-creator** [comment]
> Look into the link provided to know about my work for this project using django. https://drive.google.com/drive/folders/1TsQ0l-NGlhbgtonAMpDrwSRIcxGKLqVA?usp=sharing The landing page will be of your choice, I will just link frontend to my codebase. If the initial idea is fine, I can add more features such as providing an option to style the words in blog, uploading bluk images/videos, sending email to the admins and many more features. @himanshu007-creator Please assign me the issue if you like my work.

Hi @SnehaVeerakumar , you have really done a great job. , this is truly your issue✨

**Comment by Aditya201551** [comment]
@himanshu007-creator I would also like to collaborate on this task and I know Django pretty well and creating backend is a big task so it would be great if you have multiple people on board so if you wish I will be available🤠

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator I would also like to collaborate on this task and I know Django pretty well and creating backend is a big task so it would be great if you have multiple people on board so if you wish I will be available🤠

@SnehaVeerakumar

**Comment by SnehaVeerakumar** [comment]
> @himanshu007-creator I would also like to collaborate on this task and I know Django pretty well and creating backend is a big task so it would be great if you have multiple people on board so if you wish I will be available🤠

You are welcome, we will have discussions in discord

@himanshu007-creator assign him with me

**Comment by himanshu007-creator** [comment]
@SnehaVeerakumar  are you working on this ?!

**Comment by SnehaVeerakumar** [comment]
@himanshu007-creator until i am assigned.

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator until i am assigned.

yeah you will be assigned, and you know whole idea, please collaborate with ADITYA and i hope you both will be able to make the backend part.

**Comment by subhangi2731** [comment]
@Aditya201551 then why the issue is open

**Comment by Aditya201551** [comment]
@subhangi2731 coz it's still under development

**Comment by Aditya201551** [comment]
@himanshu007-creator please close this issue as the feature is completed

**Comment by himanshu007-creator** [comment]
DJANGO made it happen. Thanks @Aditya201551  for your work🔥
