### ISSUE TITLE
improve styling of the KMP page

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#305]
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 
[  ] Documentaion

## **Describe the bug**

@himanshu007-creator  Please let me know  exactly what changes will you like to have !!

**Comment by rohank2502** [comment]
@himanshu007-creator  Please have a look here

**Comment by rohank2502** [comment]
1. Will make the Border of the Image as per Mode ! 
2. Will make the Background of the orange color a little transparent  

@himanshu007-creator  Anything addition to this ?

**Comment by himanshu007-creator** [comment]
Yes, there was slight misunderstanding. Border of image will be as per the mode, but we need to get rid of orange color.
what i want is that  <code>kmpbox</code> background is transparent and the border of image is according to that. No orange

kmpbox: transparent by default
Dark theme:-
         image border color: white
         text-color: white

light theme:-
         image border color: black
         text-color: black

**Comment by rohank2502** [comment]
Please assign this issue to me !
