### ISSUE TITLE
Replace Canva watermarked images

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [himanshu007-creator/SFC-foundations#306]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

@himanshu007-creator  Please let me know which images to replaced by  which !

**Comment by rohank2502** [comment]
@himanshu007-creator  Please have a look here

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Please have a look here

hi! , we need to change/ remove images
- image below about us section need to be changed as it have canva watermark
- Image below join us page have same issue.it needs to be REMOVED.

wayout
You can create similar but new images (without canva watermark ) and when downloading images, select make them transparent option.

**Comment by rohank2502** [comment]
Ok please assign me an issue I will work on this will replace the images with similar with noncanva mark ! Will create a new design which doesn't have a watermark !

**Comment by saniaarora15** [comment]
@rohank2502 Can I work on this issue? I have experience with canva and will get it done asap.

**Comment by rohank2502** [comment]
@saniaarora15  We are glad you like to work on this issue but @himanshu007-creator  Is doing this design on his own because he want to discuss it with the rest team and final the design !!

**Comment by saniaarora15** [comment]
Okay.

**Comment by himanshu007-creator** [comment]
@saniaarora15  do you have a Canva pro?

**Comment by saniaarora15** [comment]
Yes

**Comment by himanshu007-creator** [comment]
Cool so I guess @rohank2502  she can work right?

**Comment by himanshu007-creator** [comment]
@saniaarora15 I'll be on my machine on 2:45, will give you the details then

**Comment by saniaarora15** [comment]
Sure

**Comment by himanshu007-creator** [comment]
@saniaarora15 , improving the NGO pictures is an inetrnal task, so can you just work on the canva water mark pictures?

**Comment by saniaarora15** [comment]
Do I have to create the exact same?

**Comment by himanshu007-creator** [comment]
not exactly, but somewhat similar,
you can change the elements within pictures, keep the text in images SAME, but change the color, so that its visible in both dark and light modes. At last while downloading these new pictures, make background transparent
Dont forget to keep the size of new images same and replace old ones (or delete) . In PR , please share github page link as well.
thanks

**Comment by saniaarora15** [comment]
Okay. Thank you.

**Comment by himanshu007-creator** [comment]
@saniaarora15  whats the progress?

**Comment by saniaarora15** [comment]
I am almost done with the banner. Will send asap.

**Comment by saniaarora15** [comment]
Should I remove the image below join us or that has to be replaced too?

**Comment by himanshu007-creator** [comment]
> Should I remove the image below join us or that has to be replaced too?

It can be replaced but reduce its height like keep the elements size same, but from top and bottom remove blank space, like we have now

**Comment by saniaarora15** [comment]
Okay

**Comment by saniaarora15** [comment]
I have made the pr. Please review it.
