### ISSUE TITLE
Contact Us Form

### ISSUE THREAD

**Issue by chitrasingla** [himanshu007-creator/SFC-foundations#31]
Hey !!
I am interested in this project as GSSOC '21 participant.
The contact us form is very simple and not looking good, I would like to work on that and will try my best to make it better

Please assign this issue to me.
Thanks.

**Comment by nandita658** [comment]
Hii... Can I work on this issue as a GSSOC participant?
I can add some font color or may be font style to it and arrange the form so that it will look nice.
Please assign this issue to me.

**Comment by neha030** [comment]
Hii..I am a GSSOC'S 21 participant  and work on this issue.
I can make it more catchy by implementing CSS.
please assign me this work.

**Comment by Naman-12911** [comment]
Hello sir , I am a participant of of GSSOC .
I can easily done the contact us form with Django backend.
Please assign me this issue

**Comment by GurleenKaur111** [comment]
Hello....I am a participant of GSSOC 21 
I would like to design the contact us form and make it more attractive .
I have my hands on practice in technologies like HTML, CSS, JavaScript and I also have Web Development Internship experience.
Can you please assign this task to me.

**Comment by Aanchal116** [comment]
Hii @himanshu007-creator , 
I would like to work on this issue as a part of GSSOC'21. I've hands-on practice in web development and also a mentorship experience. Please assign this task to me if possible.

**Comment by Ankkkitt** [comment]
Hello sir, I am a participant of GSSoC'21 
I would like to make a detailed Contact Us form and make it look more attractive using HTML, CSS, and BootStrap.
I am a beginner at Open Source Contribution and want to contribute to this issue. If you assign this task to me I will do as much as I can do for making this Contact us form better.

**Comment by drishika2002** [comment]
Hello, I am a participant in GSSOC'21 and would like to work on this issue using HTML, CSS, and BootStrap. If possible, please assign this task to me.

**Comment by Ayushbajpai19** [comment]
Can you assign this issue to me, once approved I can start working on it under GSSOC'21.

**Comment by himanshu007-creator** [comment]
sorted
