### ISSUE TITLE
Dark-mode bug in News button 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#315]
Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

The more news button text is not visible in darkmode 
!!

![Screenshot 2021-05-27 185530](https://user-images.githubusercontent.com/76584243/119834084-448d4d80-bf1d-11eb-8458-f47b6fa721da.png)

**Comment by himanshu007-creator** [comment]
@rohank2502 , please have a look at more events button in dark theme as well. Because its not same as more news, border radius and size differs.
