### ISSUE TITLE
Feed us section css improvements

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#317]
Current:-
![2021-05-27 (5)](https://user-images.githubusercontent.com/65963997/119841781-bcf70d00-bf23-11eb-8cfa-9305b8053e4e.png)

desired:-
![2021-05-27 (8)](https://user-images.githubusercontent.com/65963997/119841825-c7190b80-bf23-11eb-9878-11906cc22301.png)

Changes required:-

<code>
.feed{
border-radius: 100px;
}
.counter{
color: orange !important;
background-color: #92858552
}
</code>

As feed us section in in various pages, please be sure to change the css files for all instances.

**Comment by shriya030** [comment]
Can I work on this issue?

**Comment by himanshu007-creator** [comment]
@shriya030 , best of luck.

**Comment by rohank2502** [comment]
Lol, @himanshu007-creator  This is a repeat issue of  Which I created !! Its ok Np Great work @shriya030
