### ISSUE TITLE
Modify Hamburger Menu

### ISSUE THREAD

**Issue by shriya030** [himanshu007-creator/SFC-foundations#319]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

The text written in the hamburger menu is not visible.

## **Possible solution**

To avoid any change in the design, I'll give background color as white to the rest of the options in hamburger menu.

## **Screenshots**

![image](https://user-images.githubusercontent.com/56861600/119872830-84fec280-bf41-11eb-8a9f-be98ecc97378.png)

**Comment by rohank2502** [comment]
I think Please check once in mobile version this might be visible because we have applied background in mob version !

**Comment by shriya030** [comment]
> I think Please check once in mobile version this might be visible because we have applied background in mob version !

Nop! It's not working.

![WhatsApp Image 2021-05-28 at 4 17 23 PM](https://user-images.githubusercontent.com/56861600/119972850-5845bc00-bfd0-11eb-8879-1987f0625c4a.jpeg)

**Comment by rohank2502** [comment]
> 
> 
> > I think Please check once in mobile version this might be visible because we have applied background in mob version !
> 
> Nop! It's not working.
> 
> ![WhatsApp Image 2021-05-28 at 4 17 23 PM](https://user-images.githubusercontent.com/56861600/119972850-5845bc00-bfd0-11eb-8879-1987f0625c4a.jpeg)

OOk I think this is because of a new slider ! Well if you like to work its great @himanshu007-creator  Please check this ! Feel free to ask for any help @shriya030

**Comment by shriya030** [comment]
> > > I think Please check once in mobile version this might be visible because we have applied background in mob version !
> > 
> > 
> > Nop! It's not working.
> > ![WhatsApp Image 2021-05-28 at 4 17 23 PM](https://user-images.githubusercontent.com/56861600/119972850-5845bc00-bfd0-11eb-8879-1987f0625c4a.jpeg)
> 
> OOk I think this is because of a new slider ! Well if you like to work its great @himanshu007-creator Please check this ! Feel free to ask for any help @shriya030

Okay! @himanshu007-creator please assign me this issue.
