### ISSUE TITLE
Events page

### ISSUE THREAD

**Issue by chitrasingla** [himanshu007-creator/SFC-foundations#32]
Hey !!
I am interested in this project as GSSOC '21 participant.
The events listed on the events page are listed vertically, they can be arranged in a more better way. I would like to work on this.

Please assign this issue to me.
Thanks.

**Comment by nandita658** [comment]
Hey... We can show events as a slide show. I think it will look nice.
I am interested in this project and would like to work on this issue as a GSSOC '21 partcipant. Please assign this to me..

**Comment by nNikita1018** [comment]
I am interested in this project.
please assign to me

**Comment by Dhriti-Roy** [comment]
I would love to work on this. Kindly assigned it to me.

**Comment by himanshu007-creator** [comment]
sorted
