### ISSUE TITLE
Modify hover action in hamburger menu items

### ISSUE THREAD

**Issue by shriya030** [himanshu007-creator/SFC-foundations#320]
## Issue Type:
[  ] Bug Report 
[ x ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

Creating a hover action on hamburger menu items.

## **Possible solution**

On hovering, The text color of menu items will change to yellow same as in the case of navbar items.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by rohank2502** [comment]
@shriya030  Hey hello !! We display hamburgers in the mob version please let me know how can we hover on mobile ?

**Comment by shriya030** [comment]
> @shriya030 Hey hello !! We display hamburgers in the mob version please let me know how can we hover on mobile?

I was testing it on laptop and also saw sites that have hover action because sometimes I personally use some sites by splitting the screen, that's why I was saying.

**Comment by rohank2502** [comment]
> 
> 
> > @shriya030 Hey hello !! We display hamburgers in the mob version please let me know how can we hover on mobile?
> 
> I was testing it on laptop and also saw sites that have hover action because sometimes I personally use some sites by splitting the screen, that's why I was saying.

nice observation but I think this site is not one that is used by technical people during some work or during multitasking ! As per me mostly users will use this in full view of laptop/pc or mob ! But @himanshu007-creator Will take the final call !

**Comment by himanshu007-creator** [comment]
@rohank2502 , you are right, but we need to be future ready , hence this would increase the accessibility of website.
