### ISSUE TITLE
Changing hamburger icon

### ISSUE THREAD

**Issue by shriya030** [himanshu007-creator/SFC-foundations#321]
## Issue Type:
[  ] Bug Report 
[ x ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

Changing the burger icon of the menu to some other icon

## **Possible solution**

I will change the hamburger menu icon to another icon

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by shriya030** [comment]
> Great to see you contributing !! Please let us know which icon will you display in place of Hamburger ?

https://image.shutterstock.com/image-vector/minimal-set-hamburger-menu-flat-260nw-1501430735.jpg

One of these.

**Comment by rohank2502** [comment]
We can go with the one in the circle what you think @himanshu007-creator
