### ISSUE TITLE
Image loading bug in Projects section 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#326]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

![Screenshot 2021-05-29 122833](https://user-images.githubusercontent.com/76584243/120061149-74e9fe80-c079-11eb-9e7d-9dd376db41a2.png)

By default, the image of the Gyan project should get loaded but the image of project sampuran gets loaded !

**Comment by saniaarora15** [comment]
Can I work on this issue under gssoc 21?

**Comment by rohank2502** [comment]
> 
> 
> Can I work on this issue under gssoc 21?

For Sure why not start working on this !! And come up with a Pr till 3pm because you just have to update a path !! Please make this done as soon as possible if need help let me know !! Best of Luck

**Comment by saniaarora15** [comment]
Thank you. I will do it asap.

**Comment by saniaarora15** [comment]
I have made the pr. Please review it.
