### ISSUE TITLE
About turns yellow instead of Contact us when Contact us is opened

### ISSUE THREAD

**Issue by saniaarora15** [himanshu007-creator/SFC-foundations#338]
## Issue Type:
[x] Bug Report 

## **Describe the bug**
When Contact Us section is opened, The "About" in the header turns yellow instead of "Contact Us".

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![sfc](https://user-images.githubusercontent.com/64864806/120072115-bac1b980-c0af-11eb-9ca7-8f3a08554398.png)

**Comment by saniaarora15** [comment]
Please assign me this issue.

**Comment by himanshu007-creator** [comment]
Please submit a PR by today @saniaarora15

**Comment by saniaarora15** [comment]
Thank you. I will submit it asap.

**Comment by rohank2502** [comment]
Duplicate of #331

**Comment by saniaarora15** [comment]
It was a genuine mistake. I had submitted the pr yesterday. Will it be counted ?
