### ISSUE TITLE
Create admin dashboard

### ISSUE THREAD

**Issue by bug-debug-done** [himanshu007-creator/SFC-foundations#34]
I would like to create a responsive admin dashboard. It will be easy to use.
please assign me this issue.

**Comment by Aman1905** [comment]
Hey
I would like to work on the admin dashboard using reactjs
do assign me this issue and I will definitely try to make an interactive one

Thank You

**Comment by himanshu007-creator** [comment]
it will be needed once blog management is ready.

**Comment by himanshu007-creator** [comment]
sorted
