### ISSUE TITLE
Django as backend

### ISSUE THREAD

**Issue by SnehaVeerakumar** [himanshu007-creator/SFC-foundations#35]
I am GSSOC'21 participant. I would like to work on the backend using Django. Kindly assign me this issue to start working on it.

**Comment by CMELAKKIA** [comment]
> I am GSSOC'21 participant. I would like to work on the backend using Django. Kindly assign me this issue to start working on it.

I am GSSOC'21 participant. I would like to collaborate with Sneha to work in Django. Kindly assign me this issue.

**Comment by himanshu007-creator** [comment]
leaving the blog management system, there is not much need of a backend i suppose. Correct me if i am wrong
@SnehaVeerakumar

**Comment by SnehaVeerakumar** [comment]
Adding django in backend will complete three of your website objective. 
1. payment gateway integration
2. Create an admin dashboard
3. Blog uploading feature
 ➢ Images, videos, paragraphs can be uploaded by each admin without altering the source code. Each admin will have unique dashboard where they can also style their blog according to their wish. It also has the history of what admin has posted or deleted.
 ➢ We can also implement payment gateway integration using django.
 ➢ As it solves most of your objective, I thought it would be great to use django in backend.

@himanshu007-creator
