### ISSUE TITLE
Revamp Know-sfc page

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#363]
Merge the know sfc and objectives page, in following manner.
![WhatsApp Image 2021-05-30 at 7 08 55 AM](https://user-images.githubusercontent.com/65963997/120094803-26ebfe00-c140-11eb-875d-b0acafa7952a.jpeg)

Follow the above schema

**Comment by rohank2502** [comment]
I will like to work on this !!
