### ISSUE TITLE
Fixing spelling and grammatical mistakes in website content 

### ISSUE THREAD

**Issue by Hrishita99** [himanshu007-creator/SFC-foundations#372]
Hi! i am a fellow gssoc'21 participant and i would like to fix some bugs in the website content. As it is visible in the pic, the spelling of ones is wrong, menstruation has been spelled as mensuration and there are some grammatical mistakes also. So if you feel it's convincing enough kindly assign this issue to me. 

![sfcpic](https://user-images.githubusercontent.com/56040118/120121255-ff3c7a80-c1bf-11eb-927f-f726fff18be7.jpg)

**Comment by himanshu007-creator** [comment]
Thanks @Hrishita99 , but you are currently viewing the old website, this issue is resolved in new website, which is in development right now. You can see the new website GitHub page link from README. 
Maybe you can find more issues there🎉

**Comment by Hrishita99** [comment]
Thanks for the clarification! :)
