### ISSUE TITLE
Know more page on tablet version 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [himanshu007-creator/SFC-foundations#373]
## Issue Type:
[x ] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

I think we should make it same as mobile version !! 

![Screenshot 2021-05-31 091926](https://user-images.githubusercontent.com/76584243/120137226-776f6400-c1f1-11eb-884c-929553c174f7.png)

**Comment by rohan-kulkarni-25** [comment]
The slider is getting compressed I think like mobile version will be better I will like to work on this please assign !

**Comment by himanshu007-creator** [comment]
hi @rohan-kulkarni-25 , the NGO have proposed present views suitable given different viewports.

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> hi @rohan-kulkarni-25 , the NGO have proposed present views suitable given different viewports.

Ok
