### ISSUE TITLE
Design News section as event section 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [himanshu007-creator/SFC-foundations#375]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

This section is news section 
![Screenshot 2021-05-31 092357](https://user-images.githubusercontent.com/76584243/120137592-4cd1db00-c1f2-11eb-9789-16fb0f7a6dfe.png)

This is event section 

![Screenshot 2021-05-31 092414](https://user-images.githubusercontent.com/76584243/120137602-56f3d980-c1f2-11eb-865a-2ef96c23ddc6.png)

**Comment by rohan-kulkarni-25** [comment]
I will like to work on this !

**Comment by himanshu007-creator** [comment]
roger that
