### ISSUE TITLE
Backend image uploading issue

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#379]

**Comment by rohan-kulkarni-25** [comment]
the one of image size right !!

**Comment by himanshu007-creator** [comment]
Yup!!

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Yup!!

I think ham usse kal ke slider jaisa baan sakte means agar ham kal ke slider me konsi bhi img dale to vo almost fit ho jati 
aur jo hamne size diya ussi size me rehti

**Comment by himanshu007-creator** [comment]
yeah, we can use this in all templates

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> yeah, we can use this in all templates

tell me one thing the size of img of slider is perfect for img in blog or news ?

**Comment by himanshu007-creator** [comment]
No we have to fix size accordingly for news , blogs and event

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> No we have to fix size accordingly for news , blogs and event

ok then I will fix some and then let you know will reduce or increase them as per NGO says !!

**Comment by rohan-kulkarni-25** [comment]
@himanshu007-creator  I think we have done this !

**Comment by himanshu007-creator** [comment]
Sorted for now
