### ISSUE TITLE
Suggestion : Added Transaction Effect in Nav bar and Improve Footer Section

### ISSUE THREAD

**Issue by WebVishal** [himanshu007-creator/SFC-foundations#38]
hi, I'm Vishal, Want to Contribute to this project as participant GGso21, I have added some Transaction effect on navbar items and Improve the footer section

**Comment by Tanu-priya-Roy** [comment]
> Hi👋 thanks for creating your first issue for SFC FOUNDATIONS, Will get back to you soon !.

I would like to make a responsive footer. Please assign it to me.
