### ISSUE TITLE
3rd person from second row go out of the page in core team 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [himanshu007-creator/SFC-foundations#382]
## Issue Type:
[ x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

![Screenshot 2021-05-31 094647](https://user-images.githubusercontent.com/76584243/120139029-4002b680-c1f5-11eb-9470-e500844dfe5a.png)

**Comment by rohan-kulkarni-25** [comment]
I think we have to reduce img size or make it as mob version please let me know

**Comment by himanshu007-creator** [comment]
yup
