### ISSUE TITLE
Tablet of 10.5 inch misses the hamburger nav bar

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [himanshu007-creator/SFC-foundations#383]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

![Screenshot 2021-05-31 095134](https://user-images.githubusercontent.com/76584243/120139342-e2bb3500-c1f5-11eb-8da7-092c917a0487.png)

**Comment by rohan-kulkarni-25** [comment]
I think we have to give it drop down nav bar only because darkmode can not be adjusted

**Comment by rohan-kulkarni-25** [comment]
@himanshu007-creator  Might be done

**Comment by himanshu007-creator** [comment]
sorted by now
