### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by starlightknown** [himanshu007-creator/SFC-foundations#39]
add contributing.md to give more information about your project,how to set up and run it and welcome new contributors

**Comment by Nikitha2309** [comment]
I am a GSSoC'21 participant and I want to work on this issue. Please assign this issue to me.

I have read READ.ME and gone through the project. Hence I can create a clean understandable contribuiting.md which gives more detailed information about the contribution to the project.

Looking forward to the PR getting assigned to me.

**Comment by himanshu007-creator** [comment]
@kcoder63  go ahead!!

**Comment by mansijain980** [comment]
Can i work on it?

**Comment by himanshu007-creator** [comment]
@mansijain980  would you like to work? drop a conformation text, will assign  you immediately

**Comment by mansijain980** [comment]
@himanshu007-creator sure sir , i would like to do work on it . Please assign this to me.

**Comment by himanshu007-creator** [comment]
@mansijain980 , best of luck and please one thing. Make the contributing guidelines small, but it should be original. You are free to use emojis and fancy stuff (GIF's) but please DO NOT COPY/PASTE random CONTRIBUTING template

**Comment by rohank2502** [comment]
@himanshu007-creator  IF we need It I can go for it if no response from @mansijain980

**Comment by mansijain980** [comment]
@himanshu007-creator sir , i m working on it .due to 3 more issues it got delay . but by today evening i will commit a PR . As most of the work has been done , 
I request u to Please assign it to me.
Thanks.

**Comment by mansijain980** [comment]
@himanshu007-creator Sorry for the delay . I want to work on it .

**Comment by rohank2502** [comment]
> 
> 
> @himanshu007-creator sir , i m working on it .due to 3 more issues it got delay . but by today evening i will commit a PR . As most of the work has been done ,
> I request u to Please assign it to me.
> Thanks.

Great !! No issues @mansijain980  Come up with a Pr ! Need help feel free to ask ! Don't worry about the assignment you will get assigned !  NO issues

**Comment by rohank2502** [comment]
@himanshu007-creator  Please assign @mansijain980  This issue ! Thanks for Contribution !

**Comment by himanshu007-creator** [comment]
@mansijain980 , full steam ahead!
