### ISSUE TITLE
Map to display different branches

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#4]
SFC have 3 branches as of now.
Delhi
jalandhar
Chandigarh.
We would love if there is a google map showing all 3 branches on a map.

**Comment by khushi935** [comment]
Can I work on this? and also please guide me how to do it.

**Comment by khushi935** [comment]
Map should be display on home page ? at the bottom ?

**Comment by himanshu007-creator** [comment]
> Can I work on this? and also please guide me how to do it.

Hi @khushi935 , we will start working on project once girlscript summer of code gives it a go. Till then you can focus on the way you will implement a solution for given issue.

**Comment by khushi935** [comment]
Okay, Thank you.

**Comment by himanshu007-creator** [comment]
Have a look here first of all https://github.com/himanshu007-creator/SFC-foundations/issues/12

**Comment by Aakanksha0407** [comment]
@himanshu007-creator Can I work on this?

**Comment by Aakanksha0407** [comment]
@himanshu007-creator can I work on this as a part of GSSOC'21?

**Comment by Vartika511** [comment]
@himanshu007-creator hello sir can I work on this. I have prior experience in this as well as I have  created many websites which included map. Looking forward to work on this as a part of GSSOC'21.

**Comment by GulshanKataria** [comment]
@himanshu007-creator Hi sir. Can I work on a map to display different branches. I can create a webpage which would show all the branches on google map

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Hi sir. Can I work on a map to display different branches? I can create a webpage which would show all the branches on google map. Can you please assign this issue to me as a part of GSSOC

sure, go ahead!

**Comment by rohank2502** [comment]
Are we done with this I think we have added a site map  ? @himanshu007-creator  Please close this if we are done !
