### ISSUE TITLE
Improvise and update CODE_OF_CONDUCT.md 

### ISSUE THREAD

**Issue by Nikitha2309** [himanshu007-creator/SFC-foundations#40]
@himanshu007-creator I would like to improve CODE_OF_CONDUCT.md . It is important that contribuitors must follow a certain protocol to raise Pull Requests. Else it leads to various spam PR's which becomes a hurdle to filter manually. Hence I would like to raise this issue to improvise CODE_OF_CONDUCT.md . 

Looking Forward to getting this issue approved with GSSoc'21 label and assigned to me. Thank you

**Comment by himanshu007-creator** [comment]
@Nikitha2309 Hi , sorry for delays, but if you are still available, i will assign you this issue. Drop a confirmation please

**Comment by rohank2502** [comment]
If no response for @Nikitha2309  I will be happy to work on this  ! Let me know !

**Comment by mansijain980** [comment]
@himanshu007-creator i would like to work on it . If issue is not solved till now. Let me know please.
Thanks.

**Comment by rohank2502** [comment]
> 
> 
> @himanshu007-creator i would like to work on it . If issue is not solved till now. Let me know please.
> Thanks.

Sorry I am working on this

**Comment by mansijain980** [comment]
Its ok no problem.
Thanks.

**Comment by rohank2502** [comment]
@himanshu007-creator  Will make this done tomorrow today will work on frontend part

**Comment by mansijain980** [comment]
@rohank2502 Can i work on it ?

**Comment by rohank2502** [comment]
Ok @mansijain980  !! @himanshu007-creator  please let her work on this !! Please come up with a Pr till Tomorrow @mansijain980

**Comment by rohank2502** [comment]
Start working !!

**Comment by mansijain980** [comment]
@rohank2502 and @himanshu007-creator thank you so much

**Comment by mansijain980** [comment]
@himanshu007-creator please assign this issue to me.

**Comment by rohank2502** [comment]
> 
> 
> @himanshu007-creator please assign this issue to me.

Dont worry for assignment work and this and come up with a Pr !! Your PR will get merged !
