### ISSUE TITLE
People image

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#402]
Make them round, present behavior in web is oval images, we need to work on making images round

**Comment by rohan-kulkarni-25** [comment]
Which page ?

**Comment by himanshu007-creator** [comment]
Core team  and KMP

**Comment by rohan-kulkarni-25** [comment]
Ok, will get it done !!

**Comment by jyothi-k-g** [comment]
@himanshu007-creator  Please assign this issue to me under LGMSOC21 I would like to contribute to this issue

**Comment by himanshu007-creator** [comment]
hi @jyothi-k-g , its resolved, sorry to disappoint you, but please look  for anotehr issue
