### ISSUE TITLE
move badges to the top of Readme

### ISSUE THREAD

**Issue by Umesh-01** [himanshu007-creator/SFC-foundations#408]
## Issue Type:
- [ ] Bug Report 
- [ ]  Feature Request 
- [x] Documentaion

## **Describe the bug**
I will add links to the badges so that it can help them to navigate to different sections/ webpages like PRs, issues, contributors, etc. I will align them to the center and make them of single type so that it will look more interactive and awesome, since the badges will be colorful and more attractive than the text the users will like it.

See this image, the badge are of no use after clicking on them...

![image](https://user-images.githubusercontent.com/83420185/124014082-b109d980-da00-11eb-8c71-942d61fc01e5.png)

## **Possible solution**

![image](https://user-images.githubusercontent.com/83420185/124014119-be26c880-da00-11eb-889d-b4e55c31dec3.png)
- [ ] I will align them to the center
- [ ] I will add some more badges
- [ ] I will add links to the badges
- [ ] I will make them all of single type

**Comment by Umesh-01** [comment]
@himanshu007-creator should I make these changes??

**Comment by himanshu007-creator** [comment]
Go ahead🎉
