### ISSUE TITLE
Adjusting the CSS and changing the "read more" link to separate it from plain text

### ISSUE THREAD

**Issue by SilverGraph** [himanshu007-creator/SFC-foundations#416]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

- The "PROJECT VATAVARAN" image and text is not aligned with other divs
- The `read more` link is not clearly visible among all the plain text in "PROJECTS"

## **Possible solution**

- Adjusting the "PROJECT VATAVARAN" image and text to align with other divs in both mobile and PC view
- Adjusting the `read more` link's color to differentiate it from plain text

## **Screenshots**

![Screenshot 2021-07-05 182106](https://user-images.githubusercontent.com/74287708/124474556-4967db80-ddbe-11eb-8fe2-c9e66a02fb06.png)

![sfcfoundations com_(iPhone X)](https://user-images.githubusercontent.com/74287708/124474632-64d2e680-ddbe-11eb-9c4f-e98ea0763d32.png)

**Comment by himanshu007-creator** [comment]
Old website issue. New one is https://rb.gy/lo2cqb

**Comment by SilverGraph** [comment]
> Old website issue. New one is https://rb.gy/lo2cqb　@himanshu007-creator 

![Screenshot 2021-07-05 195553](https://user-images.githubusercontent.com/74287708/124486045-d3b63c80-ddca-11eb-8253-a65167c3fa05.png)
