### ISSUE TITLE
Adding hover/automatic calling to mobilenumber

### ISSUE THREAD

**Issue by varshitha1707** [himanshu007-creator/SFC-foundations#417]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

- The email in the contact form has a hover and if clicked will open the email page. The mobile number does not have a hover effect or if clicked, it doesn't take you to call the number.

## **Possible solution**

- just like the email in the contact form has a hover and if clicked will open the email page, I would like to add that to the mobile number as well. You can see a hover effect on the mobile number and when you click on it, it takes you to call the number.

## **Screenshots**

![Screenshot (684)](https://user-images.githubusercontent.com/69676094/124474868-afecf980-ddbe-11eb-8bf7-a6a0f3486b2d.png)
![Screenshot (683)](https://user-images.githubusercontent.com/69676094/124474994-d448d600-ddbe-11eb-90a0-5f52f7c3ca68.png)

Just like the hover on email. Similarly on the mobile number.

Please assign me this issue under **LGMSOC21**

**Comment by himanshu007-creator** [comment]
Old website issue , new one is https://rb.gy/lo2cqb
