### ISSUE TITLE
Navbar Alignment issue . 

### ISSUE THREAD

**Issue by Sarthakjain594** [himanshu007-creator/SFC-foundations#419]
## Issue Type:
[ x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

Navbar tabs are not properly aligned . 

## **Screenshots**

![Screenshot 2021-07-06 135416](https://user-images.githubusercontent.com/77162721/124567758-ea5ba280-de61-11eb-9781-dca73f982f9d.png)

I would like to  work on this issue under LGMSOC'21 . Can I ??

**Comment by himanshu007-creator** [comment]
@Sarthakjain594 , whats the device and screen size where it shows this behaviour?!

**Comment by Sarthakjain594** [comment]
Its in a laptop screen of 1920 x 1080 pixels . 
okay .

**Comment by himanshu007-creator** [comment]
Thanks for bringing to our notice. When in doubtm comment here. Me and @rohan-kulkarni-25  are there to help

**Comment by VaishnaviNigam25** [comment]
I would like to work on this. Plz assign @himanshu007-creator

**Comment by rohan-kulkarni-25** [comment]
@Sarthakjain594  it is tablet view

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> I would like to work on this. Plz assign @himanshu007-creator

Thanks for showing interest no issues many more issues will be created you can contribute to them and you can also find issues and fix them

**Comment by ankkitt19** [comment]
I would like to work on this issue . Can I ??

**Comment by himanshu007-creator** [comment]
hi @ankkitt19 , issue is in tablet mode ,for which we have not offered compatibility, so not much efforts are needed here, so closing this issue, Thanks for your interest🎉
