### ISSUE TITLE
Editing and Improving Footer

### ISSUE THREAD

**Issue by devu26** [himanshu007-creator/SFC-foundations#42]
I would like to add some of the page in footer and edit it so I request u to assign this issue to me.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by bindu030** [comment]
hi this is Bindu a GSSOC'21 participant looking forward to making the footer more attractive and informative.So please assign this task to me.

**Comment by himanshu007-creator** [comment]
#148
