### ISSUE TITLE
Home page live button position . 

### ISSUE THREAD

**Issue by Sarthakjain594** [himanshu007-creator/SFC-foundations#420]
## Issue Type:
[X] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

-It will be better if , the  flickering live button on home page , will has a fixed position . That will provide better UI experience . As for now , it is scrolling with each slide separately . 

## **Possible solution**

-   We can make it a single button and make its position property fixed , that is for now ,  a separate button is inserted for each slide . 

## **Screenshots**

![Screenshot 2021-07-06 135850](https://user-images.githubusercontent.com/77162721/124569068-3b1fcb00-de63-11eb-9da2-f69b3df2eed8.png)

**Comment by VaishnaviNigam25** [comment]
Its a simple task for me to achieve... Let me work on this plz assign ! @Sarthakjain594

**Comment by himanshu007-creator** [comment]
Hi! @VaishnaviNigam25 , issues are assigned only by the repo owners, or those who have access. In case @Sarthakjain594  dont have any problem, you can work as we follow first-come-first-serve policy

**Comment by VaishnaviNigam25** [comment]
@Sarthakjain594  PLZ assign me to this so that I can work

**Comment by Sarthakjain594** [comment]
> @Sarthakjain594 PLZ assign me to this so that I can work

Sry for being late in watching your request and without knowing your interest , I have already resolved that issue . So I hope you understand .

**Comment by Sarthakjain594** [comment]
@himanshu007-creator Can you please review my pull req ??

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Can you please review my pull req ??

Please see the comment.
Thanks
