### ISSUE TITLE
[MASTER] Adding Tribute to Contributors ! 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [himanshu007-creator/SFC-foundations#421]
## Issue Type:
[  ] Bug Report 
[x]  Feature Request 

Link to Repo :- https://github.com/rohan-kulkarni-25/Tribute-To-Contributors
Create Tribute_To_Contributors by taking references from https://youtu.be/OEURgZ_hvZo

**Comment by sharathguvvala** [comment]
I am interested.

**Comment by rohan-kulkarni-25** [comment]
Deadline by tomorrow Afternoon @sharathguvvala !! Please try to do it as soon as possible

**Comment by sharathguvvala** [comment]
I added the tribute to the contributors part, now should I open a pull request.
