### ISSUE TITLE
alignment error in KNOW SFC section

### ISSUE THREAD

**Issue by stymm-1** [himanshu007-creator/SFC-foundations#423]
The hexagonal element is not properly aligned in About Us --> Know SFC.

Please assign this issue to me.
![Screenshot 2021-07-07 005350](https://user-images.githubusercontent.com/64557006/124656004-4227f700-debe-11eb-8b8e-dc8e2454c0f6.png)

**Comment by himanshu007-creator** [comment]
@stymm-1, can you introduce the same hexagon feature plus keeping it responsive?
If yes, then issue is all yours

**Comment by stymm-1** [comment]
Yes sir,
I'll do that

**Comment by himanshu007-creator** [comment]
@stymm-1  are you a  LGMSOC participant?

**Comment by stymm-1** [comment]
yes

**Comment by himanshu007-creator** [comment]
cool
Please submit a PR by tomorrow

**Comment by himanshu007-creator** [comment]
issue resolved , Thanks @supzi-del 🎉
