### ISSUE TITLE
Changing font color of "FEEDING PAWS" page in dark mode

### ISSUE THREAD

**Issue by drishika2002** [himanshu007-creator/SFC-foundations#424]
Changing the font color of the "FEEDING PAWS" page in dark mode to increase the visibility of the text.

**Comment by himanshu007-creator** [comment]
Cool!

**Comment by himanshu007-creator** [comment]
Are you a LGMSOC participant?!

**Comment by drishika2002** [comment]
> Are you a LGMSOC participant?!

Yes sir, I am!

**Comment by himanshu007-creator** [comment]
@drishika2002 , please submit a PR by tomorrow

**Comment by drishika2002** [comment]
> @drishika2002 , please submit a PR by tomorrow

Done sir! Please tell if something has to be changed.
