### ISSUE TITLE
Typo in donate page

### ISSUE THREAD

**Issue by supzi-del** [himanshu007-creator/SFC-foundations#427]
## Issue Type:
[x] Bug Report 
[  ]  Feature Request 
[  ] Documentaion

## **Describe the bug**

- It says Futures for childrens

## **Possible solution**

- It should be "Future for Children"

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by supzi-del** [comment]
I would like to fix this under LGMSOC.

**Comment by himanshu007-creator** [comment]
@supzi-del Thanks for spotting this, please submit a PR by today.
