### ISSUE TITLE
Update Count of feeding paws

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#429]
Change value from <code>190</code> to <code>3669</code> in following lines

<a href="https://github.com/himanshu007-creator/SFC-foundations/blob/38f805accfaf0e4eff993abf06a3b44482c93bf4/index.html#L57">line 1</a>

<a href="https://github.com/himanshu007-creator/SFC-foundations/blob/38f805accfaf0e4eff993abf06a3b44482c93bf4/pages/FEED/feed.html#L149">line 2</a>

**Comment by AlkaDas991** [comment]
Hi @himanshu007-creator , I will like to contribute to it

**Comment by himanshu007-creator** [comment]
Hi @AlkaDas991 , please submit a PR by tomorrow

**Comment by AlkaDas991** [comment]
I have linked the PR, that fixes this issue, please review it once @himanshu007-creator

**Comment by himanshu007-creator** [comment]
> I have linked the PR, that fixes this issue, please review it once @himanshu007-creator

Too late, already merged🎉🟩🤞
