### ISSUE TITLE
Redirecting issue of DONATE NOW button

### ISSUE THREAD

**Issue by kevla-4121** [himanshu007-creator/SFC-foundations#43]
When we click on DONATE NOW button , it is redirecting us to home page while it should not redirect us to home page , instead it should take us on new page . I think this is an issue and I want to solve this issue. please assign this issue to me

**Comment by dibyanshu-mohanty** [comment]
Hello @himanshu007-creator , I can add an actually working donate button and I would like to work on it under GSSOC . Clicking on the Donate Now would redirect to a live page for donations

**Comment by himanshu007-creator** [comment]
Work in progress. so not an issue.
