### ISSUE TITLE
Core information link in know more

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#431]
in <code>pages/About-Us/knowsfc.html</code>, the 
user will want to view the team structure of the NGO, so there should be a long button below the description

![ss](https://user-images.githubusercontent.com/65963997/125902899-968bc585-1831-4dc0-8270-c0f5f7214c4a.png)

solution
<a href="https://gist.github.com/himanshu007-creator/28b1e347fff2bce394a6d2ffd9bb8865">Here</a> is the starter code
Button should be enclosed in an anchor tag with link to <code>../../SFC-foundations/pages/About-Us/coreteam.html</code>

Html to go <a href="https://github.com/himanshu007-creator/SFC-foundations/blob/master/pages/About-Us/knowsfc.html">here</a>
Css to go <a href="https://github.com/himanshu007-creator/SFC-foundations/blob/master/css/About-Us/knowsfc.css">here</a> 

Note* 
This feature should be responsive as well, Please try to submit a PR soon

**Comment by supzi-del** [comment]
Hey I will work on this...
