### ISSUE TITLE
HEXA-GONE!

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#433]
The Hexagon interface below <code>Out goals and objectives</code> section <a href="https://himanshu007-creator.github.io/SFC-foundations/pages/About-Us/knowsfc.html">here</a> is not mobile responsive, and doing that will be another task itself. So instead we can work another way around.

For desktop/laptop/tablets:- try to improve the alignment of the present hexagon and its components.

for mobile view:- Get rid of this code and display a single non-interacting image.

We can create a <code>hexagon.png</code>. This will contain an exact replica of the present view. It will have a hexagon and six objectives at each vertex. In hexagon, there will be a fixed text <code>Our mission</code>

**Comment by supzi-del** [comment]
I will work on this.

**Comment by himanshu007-creator** [comment]
@supzi-del  please submit a PR by today

**Comment by supzi-del** [comment]
Check the below video, as you can see the issue was not only the hexagon but also the box1 which was messing up the entire layout and responsiveness.
Hence I decided to add hexagons like this and also fixed the box1. So now it is completely responsive and clutter-free.
Please let me know if I should make a PR for the same.

**Comment by supzi-del** [comment]
https://user-images.githubusercontent.com/78655439/126040537-0a20e83d-1f23-4b6c-ad56-17bd18f8c8fc.mp4

**Comment by himanshu007-creator** [comment]
Your solution is impressive, but we need to keep the same layout as earlier.
For pc/laptop we need a hexagon with values on edges. When a value is  hovered , text in hexagon changes.


Can you try to improve upon the previous one?

Also for mobile view, just create an image of hexagon with values on edges. Thats all.


And thanks for pointing the isse of box. I hope you understood the requirements 😊

Waiting for you to work other way around

**Comment by supzi-del** [comment]
Okay but I tried doing that and everything is getting messed up! (like I tried changing the values of media query for laptop/PC)

**Comment by himanshu007-creator** [comment]
Yeah I know😐 we would really appreciate if you can make this happen🙂
