### ISSUE TITLE
Changing UI/UX design of the home page 

### ISSUE THREAD

**Issue by gunjan-g** [himanshu007-creator/SFC-foundations#435]
## Issue Type:

- [x]   Feature Request 

## **Describe the bug**
The home page is not according to the UI design , everything is blended

## **Possible solution**
1. Breaking the sections into sub-sections so that they look more eye-catching 
2. Changing the layout so that everything looks much more arranged

## **Screenshots**
![image](https://user-images.githubusercontent.com/81305824/126082392-6a5a96ad-d306-4317-b813-b9053f909dac.png)

![image](https://user-images.githubusercontent.com/81305824/126082558-1ce3f84f-1c40-4fee-bb65-84f28e1d0237.png)

**Comment by gunjan-g** [comment]
@himanshu007-creator please assign me this issue under the label LGMSOC

**Comment by himanshu007-creator** [comment]
hi @gunjan-g, you can work on this issue, but send the changes to the development branch.

**Comment by gunjan-g** [comment]
> hi @gunjan-g, you can work on this issue, but send the changes to the development branch.

ok

**Comment by himanshu007-creator** [comment]
solved by #436
