### ISSUE TITLE
Footer of web pages

### ISSUE THREAD

**Issue by machine-sg** [himanshu007-creator/SFC-foundations#45]
I am a GSSoC'21 participant and I want to improve the footer of each of the web  pages. Please assign me this.

**Comment by Naman-12911** [comment]
hello, I am a participant of GSSOC I want to fix this issue please assig me . I am waiting for your replay

**Comment by jainh6148** [comment]
Hi, I would like to work on this issue. Kindly assign it to me

**Comment by Priyanka7011** [comment]
Hi I am a GSSOC 2021 participant. I would love to work on this issue and I will give my best .
Please assign me this issue I want to contribute to this wonderful project.

Thank You

**Comment by Aman1905** [comment]
Hey I am a GSSOC 21 participant and I want to improve the footer section of the site 
1. social profiles and so on
do assign me this issue and i will definitely try to get back with  a wonderful footer section
Thank You

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by himanshu007-creator** [comment]
#148
