### ISSUE TITLE
Contact Us section design

### ISSUE THREAD

**Issue by shrishti-c** [himanshu007-creator/SFC-foundations#47]
The Contact Us section doesn't seem interactive. I can make them graceful which can interest people to join the organization. Please allow me to do the required change.

**Comment by simranbhalla3** [comment]
Hi , I am a gssoc'21 participant and would like to work on this issue, please assign it to me

**Comment by Aman1905** [comment]
Hi I am a gssoc 21 participant and I would definitely like to improve the contact us section as it is not so much user interactive in terms of its design and gracefullness. Do assign me this issue and I will definitely come back with a beautiful contact form which user would also like to fill

Thank You

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by aroma-sketch** [comment]
hey there, I am new to open source projects, and I would like to solve this issue as a small step, looking ahead to a response. it would be helpful.

**Comment by himanshu007-creator** [comment]
sorted
