### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by divyashukla23** [himanshu007-creator/SFC-foundations#49]
Hey everyone! since the website has to be created from scratch first we need a wireframe for it. 
Interested candidates can send me the wireframe on discord (you can find me easily on the project channel in the main server) and then we will proceed. 
Happy coding.

**Comment by saumyasrivastava08** [comment]
Can I work on this?

**Comment by akankshaaa-08** [comment]
@divyashukla23 Hello Ma'am. Can I have this issue assigned to me?

**Comment by himanshu007-creator** [comment]
Sorry @akankshaa-08. by mistake. First @saumyasrivastava08  have asked for it, so she will be given time. Till then you can work on your samples. Best of luck ;)

**Comment by saumyasrivastava08** [comment]
Should i start?

**Comment by himanshu007-creator** [comment]
> Should i start?

Full steam ahead!🟢

**Comment by saumyasrivastava08** [comment]
Thanks for assiging me.

**Comment by saumyasrivastava08** [comment]
![Uploading IMG_20210311_204941.jpg…]()
Something like this I am planning

**Comment by divyashukla23** [comment]
@saumyasrivastava08 U can send it on discord and i will brief about the structure that we are planning.

**Comment by divyashukla23** [comment]
One more thing for every issue we are giving 2 days deadline for example if the issue has been assigned today the PR must be sent within two days otherwise we may pass the issue to the next deserving candidate. This is done to ensure that no participant misses out the chance and the project is completed on time. :)

**Comment by saumyasrivastava08** [comment]
> One more thing for every issue we are giving 2 days deadline for example if the issue has been assigned today the PR must be sent within two days otherwise we may pass the issue to the next deserving candidate. This is done to ensure that no participant misses out the chance and the project is completed on time. :)

Link for discord Channel?

**Comment by divyashukla23** [comment]
You must have received the discord invitation for the main server on your mail right? You can look for the SFC-Website in the project channel list, I and the other mentors are there. Hope it helps.

**Comment by HelenEH0** [comment]
Hey @divyashukla23 ,
Can I contribute to this?

**Comment by divyashukla23** [comment]
@HelenEH0 Hi can you please elaborate your proposal!

**Comment by himanshu007-creator** [comment]
sorted
