### ISSUE TITLE
Header can be improved

### ISSUE THREAD

**Issue by Priyanka7011** [himanshu007-creator/SFC-foundations#50]
Hii I am a GSSOC 2021 participant.
I think the  header is too much broad it should be narrow so that the hero page of the website is properly visible and attracts the viewer. 

I can solve this issue.Please assign me this. I would give the best result .

Thank You

**Comment by RubenFalcao14** [comment]
Hii,
I'm a Participant of GSSOC'21. Please assign me this issue. I would love to work on the issue and resolve it as fast as possible.
Thank You.

**Comment by ShambhaviSharma0110** [comment]
hey I'd like to work on this... please allow me...

**Comment by Naman-12911** [comment]
Hello i want solve this issue please assign me under GSSOC.

**Comment by himanshu007-creator** [comment]
sorted
