### ISSUE TITLE
Looks of all the blogs on different topics requires improvement

### ISSUE THREAD

**Issue by drishika2002** [himanshu007-creator/SFC-foundations#51]
The blogs written for different topics can be made more attractive by changing the font size and font style. Also, some more styling can be given to the blog pages.  

_Example: In the blog "BANNING CHINESE APPS: IS IT SIGNIFICANT?" font size can be modified along with some more changes to make it attractive._

**Comment by drishika2002** [comment]
Hello, 
I am a GSSOC'21 participant and would like to work on this issue.

**Comment by himanshu007-creator** [comment]
sorted
