### ISSUE TITLE
The social profiles can be added to the footer.

### ISSUE THREAD

**Issue by ishitamundhra** [himanshu007-creator/SFC-foundations#52]
I'd love to resolve the issue. Let me know if that's fine.

**Comment by nandita658** [comment]
Can i work on this issue?

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by n-coder2k** [comment]
I would like to work on this issue as GSSOC participant.Please assign me this issue.

**Comment by aroma-sketch** [comment]
hey there, I am new to open source projects, and I would like to solve this issue as a small step, looking ahead to a response. it would be helpful  @himanshu007-creator .

**Comment by ShambhaviSharma0110** [comment]
hey I'd like to work on this... please allow me...
