### ISSUE TITLE
[UI & UX] Prototype from wireframe

### ISSUE THREAD

**Issue by archanagandhi** [himanshu007-creator/SFC-foundations#53]
Hey @divyashukla23 @himanshu007-creator, As I can see the project is building from scratch and I've also seen the wireframe has been assigned.
So after the wireframe has been made, I would like to create a prototype [UI & UX] design from the wireframe for the website.

**Comment by Elizah550** [comment]
Heyy !!! 
I can to the best wireframes to meet our requirements please assign it to me.
Thankss !!!

**Comment by himanshu007-creator** [comment]
@archanagandhi HI, please submit ideas for for UI,UX by this week. You can suggest color schema and wireframe of new website as well. Send 2 separate PR's 😉

**Comment by archanagandhi** [comment]
Thanks for assigning this to me @himanshu007-creator sir, where can I get the new wireframe for reference?

**Comment by himanshu007-creator** [comment]
> Thanks for assigning this to me @himanshu007-creator sir, where can I get the new wireframe for reference?

Hi @archanagandhi , there is no wireframe as of now. I want you to suggest color pallet ( 5 color scheme ), and font suggestion for the website

**Comment by himanshu007-creator** [comment]
inactive
