### ISSUE TITLE
Add styling to project section and section below it

### ISSUE THREAD

**Issue by ankitaugale23** [himanshu007-creator/SFC-foundations#56]
1. We can add bootstrap and CSS styling to the cards so they would look more appealing.
2. We can create or divide these 3 thing into 3 different cards with some styling effects such as on hover they would highlight the favicon and increase the size of favicon and card itself. @himanshu007-creator @divyashukla23

**Comment by Tanu-priya-Roy** [comment]
> Hi👋 thanks for creating your first issue for SFC FOUNDATIONS, Will get back to you soon !.

I would like to work on this issue. Please assign it to me.

**Comment by divyashukla23** [comment]
@Tanu-priya-Roy Please elaborate your proposal

**Comment by divyashukla23** [comment]
@ankitaugale23 i have assigned the issue to you. Work on it we will review your PR as soon as you send it.

**Comment by Tanu-priya-Roy** [comment]
Sure, will do that.

**Comment by ankitaugale23** [comment]
Sure @divyashukla23 Thanks for assigning it to me. I will make a PR by this Tuesday.

**Comment by Kavs-123** [comment]
hey @divyashukla23, please assign this issue to me!
I would love to work on the same

**Comment by himanshu007-creator** [comment]
#12
