### ISSUE TITLE
Prototype-SFC Foundations

### ISSUE THREAD

**Issue by divyashukla23** [himanshu007-creator/SFC-foundations#58]
Hey everyone! 
I would like to raise the issue for designing the prototype of the website so that we can proceed with the actual UI/UX modification and then for the backend part respectively the wireframe is already assigned ..the interested candidate can go for designing the prototype. Refer to the intro video by @himanshu007-creator for more help.
Happy Coding

**Comment by Subhangini** [comment]
Where can i get the intro video?

**Comment by jainayush362** [comment]
Hey @divyashukla23 I would like to work on Prototype Designing of the Website. I can modify the existing UI of the SFC website and make it more elegant and attractive. Could you please assign me this ?

**Comment by archanagandhi** [comment]
Hey @divyashukla23 @himanshu007-creator, yesterday itself I've created a new issue named prototype UI/UX (please check on them ) for designing the prototype. So Please assign this to me.

**Comment by Ayushbajpai19** [comment]
Can you assign this issue to me, once approved I can start working on it under GSSOC'21.

**Comment by capblack222** [comment]
Can this issue be assigned to me, I can help in writing the code as per the design for the website using HTML, CSS, JS and PHP ?
