### ISSUE TITLE
Will like to add techstack section used ( logo also )

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#59]
I will like to add the tech stack used and also their logo this will make the read me file more attractive !! Will start the work as soon as I get assigned

**Comment by himanshu007-creator** [comment]
@rohank2502  Go ahead
you can add html, css, js, django, php, mysql and any other that you discover

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 Go ahead
> you can add html, css, js, django, php, mysql and any other that you discover

Ok will do in 10 mins

**Comment by rohank2502** [comment]
Done Already ! BY me LOL
