### ISSUE TITLE
Color scheme + Fonts suggestions for entire project

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#6]

**Comment by khushi935** [comment]
![Screenshot (71)](https://user-images.githubusercontent.com/62712155/107840621-4bfb7180-6dda-11eb-9f51-e4eda945fc1c.png)

![Screenshot (73)](https://user-images.githubusercontent.com/62712155/107840630-59186080-6dda-11eb-9dbd-320f27f66be0.png)

![Screenshot (72)](https://user-images.githubusercontent.com/62712155/107840698-f8d5ee80-6dda-11eb-839e-9e5bb9c1059c.png)
This are some of changes that I feel.

**Comment by himanshu007-creator** [comment]
> ![Screenshot (71)](https://user-images.githubusercontent.com/62712155/107840621-4bfb7180-6dda-11eb-9f51-e4eda945fc1c.png)
> 
> ![Screenshot (73)](https://user-images.githubusercontent.com/62712155/107840630-59186080-6dda-11eb-9dbd-320f27f66be0.png)
> 
> ![Screenshot (72)](https://user-images.githubusercontent.com/62712155/107840698-f8d5ee80-6dda-11eb-839e-9e5bb9c1059c.png)
> This are some of changes that I feel.

Good, but @khushi935 , we have to make a new website from scratch. We will use old website just as a source of motivation, to know how was it done previously.

We aim to build an Amazing new website for the project, that will have  added functionality and better user experience.

**Comment by khushi935** [comment]
Okay, I got it😊

**Comment by himanshu007-creator** [comment]
Have a look here first of all https://github.com/himanshu007-creator/SFC-foundations/issues/12

**Comment by Mukta-Sawant** [comment]
@himanshu007-creator  Can I work on this issue? I would like to solve this problem as a part of GirlScript Summer of code 2021.

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Can I work on this issue? I would like to solve this problem as a part of GirlScript Summer of code 2021.

Hi @Mukta-Sawant , you are most welcomed to work on this issue, Please have a look <a href="https://github.com/himanshu007-creator/SFC-foundations/issues/12">here</a> and you will know the drill.
Best of luck.

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by himanshu007-creator** [comment]
@Mukta-Sawant   yes you can work on it. We just need an idea like how you will proceed. As we are redesigning everything so everything will be changes and so will the site structure. We just need to know how you are going to implement it. Prepare a prototype of code and send it within this week. Best of luck!

**Comment by mansijain980** [comment]
@himanshu007-creator  sir can i implement it ? I will send u a prototype of this code . 
Please Assign it to me

**Comment by Mukta-Sawant** [comment]
@mansijain980 I don't mind working together with you on this issue, only if you and @himanshu007-creator are okay with it!

**Comment by himanshu007-creator** [comment]
@mansijain980  make it soon

**Comment by mansijain980** [comment]
@himanshu007-creator i was working on a hackathon and sry for delay .....I will submit it soon.
Thanks

**Comment by himanshu007-creator** [comment]
doesn't work
