### ISSUE TITLE
Will like to add the automatic updating contributor section !! 

### ISSUE THREAD

**Issue by rohank2502** [himanshu007-creator/SFC-foundations#60]
I will like to add a feature which will keep the contribution section in read me updated automatically !! Will start on this issue as soon as I get assigned !!

**Comment by himanshu007-creator** [comment]
Would you like to work?  @rohank2502  on this issue?!

**Comment by Pallavi-02** [comment]
I'm the Participant of GSSOC'21. Please assign me this issue.I would love to work on this

**Comment by rohank2502** [comment]
> 
> 
> Would you like to work? @rohank2502 on this issue?!

Yes I will like to Sorry Due to pending issues I forget to look towards this will start to as soon as I get assigned !!

**Comment by naqeeb2710** [comment]
can u please assign me this issue?

**Comment by vismitap** [comment]
May I work on this issue as a part of GSSoC?

**Comment by himanshu007-creator** [comment]
@rohank2502  send a pr for this by this week
