### ISSUE TITLE
Header (navbar and background) Size and Appearance

### ISSUE THREAD

**Issue by nandita658** [himanshu007-creator/SFC-foundations#62]
Hey everyone...
I can work on resizing the navbar and instead of displaying images of different size, I can add a background with slideshow, which will look more attractive. I can start working on this issue as soon as you assign it to me.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by himanshu007-creator** [comment]
sorted
