### ISSUE TITLE
Using cards and some css for projects section

### ISSUE THREAD

**Issue by nandita658** [himanshu007-creator/SFC-foundations#63]
In projects section, instead of using a single white block, I can use cards and also adjusting image and text size for more beautiful alignment. I can start working on this issue as soon as you assign it to me.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by nandita658** [comment]
@himanshu007-creator Can I start working on this?

**Comment by Elizah550** [comment]
I have a great experience for CSS i can assure that i can make the website responsive and user friendly.Assign it to me. 
Thanks !!!

**Comment by anushka-srivastava22** [comment]
I am gssoc participant. Can i work upon this issue...????

**Comment by himanshu007-creator** [comment]
sorted
