### ISSUE TITLE
success stories

### ISSUE THREAD

**Issue by bindu030** [himanshu007-creator/SFC-foundations#65]
looking forward to adding the so far success stories on the websites in order to show people how this NGO organization impacted in making things better. Thank You.

**Comment by Elizah550** [comment]
Heyy!!
I can make this happen I have hands on experience for this will definitely have great look for the website for sure.
Please assign it to me.
Thanks!!!!

**Comment by himanshu007-creator** [comment]
unwanted feature. Still thanks for your interest. Please look into active issues!
