### ISSUE TITLE
Style the hero image section

### ISSUE THREAD

**Issue by rray14** [himanshu007-creator/SFC-foundations#66]
Hi my name is Ardra, participant of GSSoC'21
I can contribute by styling the hero image section of the current site
Being the first content a visitor encounters on the site, it could be made to represent the theme of your site
Please assign me this issue
Thanks!

**Comment by ShambhaviSharma0110** [comment]
Hey, I'm interested in this project could you please allow me to work on it?

**Comment by himanshu007-creator** [comment]
have a look at #12

**Comment by himanshu007-creator** [comment]
sorted
