### ISSUE TITLE
Removing CMS and theme detail from footer

### ISSUE THREAD

**Issue by ApekshaAgarwal** [himanshu007-creator/SFC-foundations#67]
Theme and CMS details in the footer will increase more vulnerability chances to the site so these details should be removed from the front end. I would like to make this enhancement. Please @himanshu007-creator allow me t work on this and assign it to me with gssoc label.

**Comment by ApekshaAgarwal** [comment]
@himanshu007-creator  please assign this issue to me. I would like to work on this.

**Comment by himanshu007-creator** [comment]
sorted
