### ISSUE TITLE
Contact us form thanks email

### ISSUE THREAD

**Issue by ApekshaAgarwal** [himanshu007-creator/SFC-foundations#68]
Currently on site the Contact us form is not sending and thanking email for contacting. I would like to work on this feature. @himanshu007-creator , please assign this issue to me and add label gssoc to it.

**Comment by Naman-12911** [comment]
I want to work on this issue please assign me under GSSOC.

**Comment by agamjotsingh18** [comment]
Would like to work on this issue please assign it to me ... Regards!

**Comment by himanshu007-creator** [comment]
sorted
