### ISSUE TITLE
Wrong Icon for youtube

### ISSUE THREAD

**Issue by ApekshaAgarwal** [himanshu007-creator/SFC-foundations#69]
On front end social media section flickr icon is displayed with the youtube link. I would like to work on this and fix it. @himanshu007-creator , please assign this issue to me under gssoc label.

**Comment by Ayushbajpai19** [comment]
Can you assign this issue to me, once approved I can start working on it under GSSOC'21.

**Comment by Ankkkitt** [comment]
Hey, it is showing the Flickr icon on the youtube link. I would like to work on this issue. Could you please assign this issue to me? 
I am a participant of GSSoC'21. 
@himanshu007-creator

**Comment by himanshu007-creator** [comment]
old website issue
