### ISSUE TITLE
Readme reloaded

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#7]
We need to create a new readme. Keep the main content same, just add a contributor's table. Also make use of some GIF's and emojis to make it look awesome.

**Comment by himanshu007-creator** [comment]
Have a look here first of all https://github.com/himanshu007-creator/SFC-foundations/issues/12

**Comment by Subhangini** [comment]
I would like to work on this issue .Please assign this to me.

**Comment by himanshu007-creator** [comment]
HI @Subhangini GSSOC will begin on 1st march, then only issues will be alotted . Please have a look here https://github.com/himanshu007-creator/SFC-foundations/issues/12

**Comment by Subhangini** [comment]
>HI @Subhangini GSSOC will begin on 1st march, then only issues will be alotted . Please have a look here #12
Ok @himanshu007-creator .Will wait till then.

**Comment by chehak123** [comment]
Hi, I want to work on it as a participant in GSSOC'21, can you please assign this issue to me?

**Comment by himanshu007-creator** [comment]
@chehak123  Best of luck!

**Comment by mansijain980** [comment]
@himanshu007-creator , I want to work on it as I already volunteering in a NGO so it will be easy for me to work for this website .
I am  a GSSOC participant.
Assign it to me please

**Comment by himanshu007-creator** [comment]
@chehak123  status report?

**Comment by mansijain980** [comment]
Can u please assign this issue to me?

**Comment by himanshu007-creator** [comment]
> Can u please assign this issue to me?

wait till saturday, the its all yours

**Comment by mansijain980** [comment]
@himanshu007-creator Can i please start to work on this issue now?

**Comment by himanshu007-creator** [comment]
@mansijain980 any updates?

**Comment by mansijain980** [comment]
@himanshu007-creator sir ,  i had started work on some other issue sir . i will give it to u by tomorrow evening for sure.
Thanks.

**Comment by AnkushSinghGandhi** [comment]
I would like to work on this issue. can you assign this to me. I will try to complete it by tommorow.

**Comment by himanshu007-creator** [comment]
@AnkushSinghGandhi  please submit a PR by tomorrow. DONT REMOVE THE BANNER AND DESCRIPTION OF NGO. rest , use your creativity.

**Comment by AnkushSinghGandhi** [comment]
and what about contributors table

**Comment by himanshu007-creator** [comment]
> and what about contributors table

keep it as well👍🏽

**Comment by AnkushSinghGandhi** [comment]
ohk

**Comment by AnkushSinghGandhi** [comment]
can i redesign the logo of sfc

**Comment by himanshu007-creator** [comment]
> can i redesign the logo of sfc

NOPS! we got it coevred. Just focus on anything you feel is wrong except LOGO, NGO's description, contributor's table.

**Comment by AnkushSinghGandhi** [comment]
ok

**Comment by IshanPiplani** [comment]
can i work on this
