### ISSUE TITLE
Updation in Home Page

### ISSUE THREAD

**Issue by sudeepshukla930** [himanshu007-creator/SFC-foundations#72]
Hey @himanshu007-creator , @divyashukla23 , I was just viewing the website , I found that :

1. There is a lack of hover effect in the header
2. A little bit of enhancement in style
3. the header is long.

what your view on it.
Waiting for your response @himanshu007-creator, @divyashukla23.

**Comment by divyashukla23** [comment]
@sudeepshukla930 yes sure go ahead.
i am adding labels to the issue and assigning it to you.

**Comment by sudeepshukla930** [comment]
Thankyou so much

**Comment by sudeepshukla930** [comment]
@divyashukla23 @himanshu007-creator  .,  The source code  is little bit messy , I tried to do changes  in css files but nothing is reflecting on the home page.
Can you please guide me .

**Comment by mansijain980** [comment]
@himanshu007-creator @divyashukla23 I want to work on this issue from the start as i know web dev so i easily can work .
Please assign it to me.
I am a GSSOC participant .
THanks

**Comment by sudeepshukla930** [comment]
@divyashukla23  @himanshu007-creator  , I am working on the issue and i also frontend web dev ... I am continuing with my work.
Thankyou

**Comment by himanshu007-creator** [comment]
@sudeepshukla930  HI , please have a look at latest announcement #12

**Comment by mansijain980** [comment]
> @himanshu007-creator @divyashukla23 I want to work on this issue from the start as i know web dev so i easily can work .
> Please assign it to me.
> I am a GSSOC participant .
> THanks

can i?
