### ISSUE TITLE
Positioning and responsiveness on Core Team pages

### ISSUE THREAD

**Issue by Vanshikaa00** [himanshu007-creator/SFC-foundations#73]
1) Hello, on Core team Jalandhar, delhi and chandigarh page, the content inside the carousel displaying the team members list is positioned to left and also touching the dots below (the circled ones)
![image](https://user-images.githubusercontent.com/53425575/111188460-144f3780-85db-11eb-8322-4355a8f4add2.png)

2) When this page is viewed on a smaller device/mobile, the team members pictures come over the top of the whole slide like this: 
![image](https://user-images.githubusercontent.com/53425575/111188961-9a6b7e00-85db-11eb-930a-2b4d6281c1e4.png)
 
 ![image](https://user-images.githubusercontent.com/53425575/111189002-a48d7c80-85db-11eb-8036-e31d551e91bd.png)

I would like to work on this issue under GSSOC'21. Can you please assign it to me?
Thank you

**Comment by agamjotsingh18** [comment]
I can take this issue and make it perfect... Regards!

**Comment by himanshu007-creator** [comment]
Hi, this issue is regarding the old code, so not needed.  You can instead try for other issues.
