### ISSUE TITLE
The contact us form should have some styling

### ISSUE THREAD

**Issue by Akibsheikh48** [himanshu007-creator/SFC-foundations#75]
The contact us form should have some styling and also have some background color or image and social media icons have some cool effect on it 

Waiting for your response @himanshu007-creator, @divyashukla23.

**Comment by Akibsheikh48** [comment]
I want to contribute to this as a GSSOC'21 participant. please assign it me.

**Comment by divyashukla23** [comment]
@Akibsheikh48 done adding with labels and assigned to you. Good luck!

**Comment by Akibsheikh48** [comment]
Hey @divyashukla23, thank you for assigning the issue

**Comment by ShambhaviSharma0110** [comment]
hey I'd like to work on this... please allow me...

**Comment by RahulBansal0502** [comment]
I also want to work on this issue. Please allow me.

**Comment by Ayushgup85** [comment]
Is this issue still open?

**Comment by himanshu007-creator** [comment]
> Is this issue still open?

Nops.
