### ISSUE TITLE
Typing effect on "Educate to Elevate" ""Each One Feed One" "storynama"

### ISSUE THREAD

**Issue by bitaashna** [himanshu007-creator/SFC-foundations#76]
I would like to emphasize the the heading "Educate to Elevate" ""Each One Feed One" "storynama" by adding a typing effect on the word  using javascript. It would enhance the look and feel of the header section.
**Please assign me this issue under the label **GSSOC'21****
**I would like to contribute to it.**
![20210315_192206](https://user-images.githubusercontent.com/57864526/111223178-cea66500-8602-11eb-9952-5d8a2b8b4696.gif)

I have shown a demo of what I will be doing in the above attached GIF
Please assign me @himanshu007-creator , @divyashukla23.

**Comment by himanshu007-creator** [comment]
hi @bitaashna , are you still active, this issue can be assigned to you if you say so

**Comment by himanshu007-creator** [comment]
not needed. Thanks, please look into other open issues :)
