### ISSUE TITLE
Adding dark mode to the website

### ISSUE THREAD

**Issue by bitaashna** [himanshu007-creator/SFC-foundations#77]
I would like to add a new feature dark and light mode switching on website so that user can use it according to their preferences
I would like to contribute to it as a part of GSSOC'21
Please assign me this issue @himanshu007-creator @divyashukla23

**Comment by ShambhaviSharma0110** [comment]
hey I'd like to work on this... please allow me...

**Comment by himanshu007-creator** [comment]
Sorry, but this feature has been already added.
