### ISSUE TITLE
SUGGESTIONS

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#8]
If any developer have any suggestions for the project, you are welcome to reply in this issue. If found useful, you might get a chance to work on the same.

**Comment by Thiyageshkanna** [comment]
I would like to add Pre-loader for this Webpage and I would like to change the footer part.

**Comment by himanshu007-creator** [comment]
Have a look here first of all https://github.com/himanshu007-creator/SFC-foundations/issues/12

**Comment by sheetalj2205** [comment]
I think the header and footer of the page could be better like the height of the header and in the footer names and other information can be more managed. I would like to work on this.

**Comment by himanshu007-creator** [comment]
> I would like to add Pre-loader for this Webpage and I would like to change the footer part and Nav-bar.

Send a code sample (PR)

**Comment by himanshu007-creator** [comment]
Not needed anymore
