### ISSUE TITLE
Label commenting bot

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/SFC-foundations#83]
check <a href="https://github.com/marketplace/actions/label-commenter#workflow-setting">this</a>. I would love to have this installed for our repo here.
I would like it to generate different messages for following labels:-

1) gssoc21
2) level0
3) level1
4) level2
5) level3
6) under review
7) changes requested

Be quick to grab this issue. To get the PR merged, do attach screen shots of this thing working

**Comment by Kriti-bit** [comment]
I am a GSSOC participant, I would like to work on this

**Comment by himanshu007-creator** [comment]
@Kriti-bit  Best of luck, send a PR by this Saturday 5 p.m.
