### ISSUE TITLE
Social Media Icons

### ISSUE THREAD

**Issue by RahulBansal0502** [himanshu007-creator/SFC-foundations#84]
Wanted to change the representation of icons of social media. Please assign this issue to me. I am a GSSOC participant @himanshu007-creator @divyashukla23

**Comment by mansijain980** [comment]
@himanshu007-creator I want to work on this issue .

**Comment by dhruvdy** [comment]
@himanshu007-creator can you please assign this to me. I want to work on these social media icons

**Comment by himanshu007-creator** [comment]
old codebase issue
