### ISSUE TITLE
[Fix] Disalignment in cards 

### ISSUE THREAD

**Issue by mirakiii** [himanshu007-creator/SFC-foundations#85]
## Disalignment in cards under projects section 
This alignment is not going well with design of website , this needs  to be fix so that all three cards are aligned in same height.

![image](https://user-images.githubusercontent.com/68226051/111514394-b572f500-8777-11eb-8bae-fc3d7a9608b5.png)

I can fix this, you may assign this to me under Gssoc'21 :four_leaf_clover: 
Thankyou :)

**Comment by himanshu007-creator** [comment]
old codebase issue
