### ISSUE TITLE
Enhancements in footer of the home Page

### ISSUE THREAD

**Issue by Deeks900** [himanshu007-creator/SFC-foundations#86]

**Comment by Deeks900** [comment]
I want to do some enhacements in the footer of the home page so that it can contain all the links in a more structured way and I will add some icons and effects to the links on the footer.I want to contribute as GSSOC'21 participant.So could u please assign this issue to me

**Comment by agamjotsingh18** [comment]
Would like to work on this issue please assign me ?    Regards!

**Comment by himanshu007-creator** [comment]
@Deeks, please have a look on the present footer. If more changes are needed, do let me know

**Comment by himanshu007-creator** [comment]
#148
