### ISSUE TITLE
Enhancing the Readme.MD file by adding valuable stuff

### ISSUE THREAD

**Issue by RaveenaBhasin** [himanshu007-creator/SFC-foundations#88]
I would like to add the tech stacks used in the readme.md file and would like to add project admins and contributors list in the readme file to make it more attractive.
Please assign this issue to me.

**Comment by Nishayadav-bit** [comment]
I  would like to work on this issue . Please assign to me

**Comment by Nishayadav-bit** [comment]
Please mark the label on this issue .
I want to work on it behalf of GSSOC'21

**Comment by himanshu007-creator** [comment]
@Nishayadav-bit , techstack is already added
