### ISSUE TITLE
making entire div clickable

### ISSUE THREAD

**Issue by Priyanshi-Sharma-142** [himanshu007-creator/SFC-foundations#94]
Having the entire div clickable will make it easy for the users, they don't have to click on the "read more" every time they want to open a project.

Make the entire div clickable so that they can click anywhere inside the box to open the page.

I would like to try implementing this.

**Comment by Priyanshi-Sharma-142** [comment]
I am a gssoc participant. please assign this issue to me.

**Comment by himanshu007-creator** [comment]
old codebase issue
